import time
import itertools

test = 0
__author__ = 'Carl Rodriguez'
# I did not work together with anyone else on this project

def lcs_dyn(a, b):
    m = len(a)
    n = len(b)
    answer = ""
    myArr = [[0 for _ in range(m + 1)] for _ in range(n + 1)]
    myArr2 = [[0 for _ in range(m + 1)] for _ in range(n + 1)]

    long_run = False
    for i in range(1, m + 1):
        if i % 100 == 0:
            if not long_run:
                long_run = True
                print("Hundreds of characters: ",end="")

            print(".",end="")
        for j in range(1, n + 1):
            if b[j - 1] == a[i - 1]:
                myArr[i][j] = myArr[i - 1][j - 1] + 1
                myArr2[i][j] = 2
            elif myArr[i][j - 1] >= myArr[i - 1][j]:
                myArr[i][j] = myArr[i][j - 1]
                myArr2[i][j] = 1
            else:
                myArr[i][j] = myArr[i - 1][j]
                myArr2[i][j] = 0
    if long_run:
        print(" Done!")

    x = m
    y = n
    answer = ""

    while x > 0 and y > 0:
        if myArr2[x][y] == 2:
            answer = a[x - 1] + answer
            x -= 1
            y -= 1
        elif myArr2[x][y] == 1:
            y -= 1
        else:
            x -= 1


    #
    # print(b)
    # print(a)
    # for index,asdf in enumerate(myArr):
    #     # print(a[index],end="")
    #     for asdf1 in asdf:
    #         print(asdf1,end="")
    #     print()
    # print("--------------")
    # for asdf in myArr2:
    #     for asdf1 in asdf:
    #         print(asdf1,end="")
    #     print()

    return (myArr[i][j], answer)


def lcs_rec(a, b):
    recursions = 0
    a = lcs_rec2(a, b, len(a) - 1, len(b) - 1, recursions)

    return a


def lcs_rec2(a, b, i, j, recursions):
    recursions += 1
    if i < 0 or j < 0:
        return (0,"")
    if a[i] == b[j]:
        recurse = lcs_rec2(a, b, i - 1, j - 1, recursions)
        return (recurse[0]+1,recurse[1]+a[i])
    else:
        left = lcs_rec2(a, b, i - 1, j, recursions)
        up = lcs_rec2(a, b, i, j - 1, recursions)
        return left if left[0] > up[0] else up



def lcs_brute(a, b):
    max_len = 0
    max_sub = ""
    test = ""
    for i in range(0, 2 ** len(a)):
        for j in range(0, len(a)):
            if (i // (2 ** j)) % 2 == 0:
                test += a[j]
        if len(test) < max_len:
            tmp = 0
        else:
            tmp = match(test, b)
        if tmp > max_len:
            max_len = tmp
            max_sub = test
        test = ""

    return (max_len, max_sub)


def match(sub, string):
    track = 0
    if len(sub) == 0:
        return 0
    for elem in string:
        if sub[track] == elem:
            track += 1
            if track == len(sub):
                return track

    return 0 if track < len(sub) else track


def printArr(multi):
    for j in range(0, len(multi[0])):
        for i in range(0, len(multi)):
            print(multi[i][j], end=" ")
        print()


def lcs_brute2(a, b):
    max = 0
    tmp = 0
    start = 0
    longest = ""
    test = ""
    binary = ""
    for i in range(0, 2 ** len(a)):
        for j in range(0, len(a)):
            if (i // (2 ** j)) % 2 == 0:
                binary += "1"
                test += a[j]
            else:
                binary += "0"
        if len(test) < max:
            tmp = 0
        else:
            tmp = match(test, b)
        if tmp > max:
            max = tmp
            longest = test
            print(binary, " current max")
        else:
            print(binary)
        binary = ""
        test = ""
    print(longest, " is the match")
    return max

def run_test(a,b,algorith):
    types = {0:("Brute",lcs_brute),1:("Recursive",lcs_rec),2:("Dynamic",lcs_dyn)}
    run = types.get(algorith)
    if run:
        print("Running LCS",run[0],"on size",len(a),"by",len(b))
        before = time.time()
        res = run[1](a,b)
        after = time.time()
        print("The solution with a length of",res[0],"is",res[1])
        print("Time elapsed is",after-before)
        print()
        return res
    else:
        print("Algorithm not found")


a10 = "TGTTTCCCGT"
b10 = "GCTCGCATTA"

a15 = "GATTTAGATTATTGC"
b15 = "AGGTCTAGAATATTG"

a20 = "CCGCTTCTTAAGGGAGTATA"
b20 = "GGATAGACGATCGTCTCAAA"

a100 = "TGTGTGACTTCCTGGCTACTACCCGTTGCATCTAGTTACAGGTATCACTAACGTCTGATTATGCAGCTCCCAATTAGGGCCGTGTGTCAGGACTTTTTGA"
b100 = "CGGGTTCGCCCGCGGGAGTAACTGTTACAGCAAAGTACTGTACCGCAACGCTGGGGATGATATGTACGGGGCTTGTGTGATTAGACAGGGCCTGAGCTCC"

# run_test(a10,b10,0)
# run_test(a10,b10,1)
# run_test(a10,b10,2)

run_test(a15,b15,0)
run_test(a15,b15,1)
run_test(a15,b15,2)

#
# run_test(a20,b20,0)
# run_test(a20,b20,1)
# run_test(a20,b20,2)
#
# run_test(a100,b100,2)

# run_test(a1000,b1000,2)
#
# run_test(a10000,b10000,2)


a1000 = "AAGTTGGTACCCTCTATTTATGCCCGGATCTTGATCTCCAGACAGGGGGTAAAGGCATGGGCCAGTTACTACCCGTATTTAGGTTGTATTCCGCATCTGAAGGCGCCGTAGTGA" \
        "TAGGCGCTGAACTGAATGCATAATGGCCAATTTGACACCTGTGGTTGTCCTCACCAATACCTGGCCCTGTCGCTCCTAATACCCCGAAGCATAGAGCAGGTCCTAACCGGATAA" \
        "CTCAGCTAACAGAAACTCCCCCAAGAACTAAGCACACCCAATGTGAACGTAGTCCGCTAGTGCTAGCGCTTCCTTACAGCCTTTCCTTATGGTATCTATGAGCTGGCCTAGTAT" \
        "ACAGGTTCTCCGACAACCAAGCCTCTCGCTGCGTTCGAGCACTGCCCGATGGCTTTGACGCGAGAGCGCTGGGTCTCATAATAAGATGGGGCGCTGTAGCGTAGTATCCCTCTC" \
        "GAGGGGACCCCGTAATGATGACATAGGTACATGCTGATAGAGGGGTCGACGGTCATTAATAACGTCCGGCTCGGCCACCCCTAGACTAGAGGGGAGAAGTTTCAGTATCTCTCG" \
        "TTTTGAATGGTACATATAAGCCTAAAGACGAGGGTAGGGTCACTAAAACTAAGTGAGCAACGTGCGGTACTGTCCTAGGCGGGCTTGACATTATACTCACTACGTTGGTTTCGC" \
        "GATGAGTCACAGGACTTTTCAGACCATGTGTCTGCCTCTAGGACCAATGGCTGGGTGTTGGTATACAACAGAGTCATTCATTTACGTCGTATATTCTAATACCACTCTTCACAC" \
        "GTCGAAATTTTCTGAGTTTCGACTACGCTTGTGAGCACTTCCTACTTGGTTAAGCAAGTGTGGGACGGCCTTCTTGGGCCAGGACGTAGGTTCCGCTGACAGTACAACGGAGAC" \
        "CAGAAAAGCTATTCAAGAGAGACATGGTACAGTTCTGTATGCATAAGCGTGCCCCTTAGCGCAACTGGCGTATACCGTCGATTCAGGG"
b1000 = 'GTTCGTTCATGACTGTCTAAACCTATTCGACGTGCGCCCTTTAGAGGATCATTCTAGATT' \
        'GTATGAGACCGATAAGATGAACATTTTATCAATTCCGCGCGGGGCTACAATATGATCTTG' \
        'ATAATTGTGGTATAAGAGACGATAAAGGCGATTTTCTATCAATCCATCTGACAAACCGTC' \
        'TCTAGCATCAATGCAACGCGTTTGGTTGGCCTAGTGGCGTTAGTGAATGGGGACCAGTTC' \
        'AGTATCGCCCATCGGACTTGAACAATAAGCGTGAACGGACCCAAACTTTTATGCCCGGCC' \
        'GGTTTCGACCCCGTTGCGACGAGTTATCATTTCAGCACGAGGACATGGTCCCGGTTTGAG' \
        'ACTCGTAAAACCCTACCTAGCACGGTATTCCGGACACTAATATAAAATGAATACCTGCGA' \
        'TAATAGATCAAGCGCTACAGCCCGGGCCCAGCTACCCGGATATAAATCTAAATGTTGCAT' \
        'AAACCATTATTGTACCTCAACTTGAGTTCGATAGGCCGCGCACTGTGGCTTTGCCATGCC' \
        'TACGCTTCACCATAGACTACACGTGAAAATTCGCATTAGCCTACACGACACGCCCGAGTC' \
        'TAAATGTTCCTCGAAGAACAATGTTGCCAAAGTTCTATTGATTACACACAAGCGCACTAA' \
        'AAGACAAAATTTATGGCCAGGGGCGGTAGTAGAATAGCAAGGTGAGTTGTTCGCAGGCTA' \
        'CATGCGATGCGATAGTATACTCGCGACCGGAGGGGGTCCCACACCCTTATGCTGATATTG' \
        'CTTATGCATATGGCTACGATACAGCCGAAACCAAACGGCTAAATATTAGTACCTAGTTTC' \
        'GAAAACATGGCTTGCGCATCACCTTCCATAAGGACGACGTCGAGCCAAGCGCATAGAAGG' \
        'CTTTATAATTATAAGGACAATGGGGACATCTCGTCCTGGTGTATTCGTCCAAGTGCTTGG' \
        'TGAAATCATCACGACCCATAGATGCTTCATCAGCATCATC'


a10000 = "AAGTTGGTACCCTCTATTTATGCCCGGATCTTGATCTCCAGACAGGGGGTAAAGGCATGGGCCAGTTACTACCCGTATTTAGGTTGTATTCCGCATCTGAAGGCGCCGTAGTGA" \
         "TAGGCGCTGAACTGAATGCATAATGGCCAATTTGACACCTGTGGTTGTCCTCACCAATACCTGGCCCTGTCGCTCCTAATACCCCGAAGCATAGAGCAGGTCCTAACCGGATAA" \
         "CTCAGCTAACAGAAACTCCCCCAAGAACTAAGCACACCCAATGTGAACGTAGTCCGCTAGTGCTAGCGCTTCCTTACAGCCTTTCCTTATGGTATCTATGAGCTGGCCTAGTAT" \
         "ACAGGTTCTCCGACAACCAAGCCTCTCGCTGCGTTCGAGCACTGCCCGATGGCTTTGACGCGAGAGCGCTGGGTCTCATAATAAGATGGGGCGCTGTAGCGTAGTATCCCTCTC" \
         "GAGGGGACCCCGTAATGATGACATAGGTACATGCTGATAGAGGGGTCGACGGTCATTAATAACGTCCGGCTCGGCCACCCCTAGACTAGAGGGGAGAAGTTTCAGTATCTCTCG" \
         "TTTTGAATGGTACATATAAGCCTAAAGACGAGGGTAGGGTCACTAAAACTAAGTGAGCAACGTGCGGTACTGTCCTAGGCGGGCTTGACATTATACTCACTACGTTGGTTTCGC" \
         "GATGAGTCACAGGACTTTTCAGACCATGTGTCTGCCTCTAGGACCAATGGCTGGGTGTTGGTATACAACAGAGTCATTCATTTACGTCGTATATTCTAATACCACTCTTCACAC" \
         "GTCGAAATTTTCTGAGTTTCGACTACGCTTGTGAGCACTTCCTACTTGGTTAAGCAAGTGTGGGACGGCCTTCTTGGGCCAGGACGTAGGTTCCGCTGACAGTACAACGGAGAC" \
         "CAGAAAAGCTATTCAAGAGAGACATGGTACAGTTCTGTATGCATAAGCGTGCCCCTTAGCGCAACTGGCGTATACCGTCGATTCAGGG" \
         "AAGTTGGTACCCTCTATTTATGCCCGGATCTTGATCTCCAGACAGGGGGTAAAGGCATGGGCCAGTTACTACCCGTATTTAGGTTGTATTCCGCATCTGAAGGCGCCGTAGTGA" \
         "TAGGCGCTGAACTGAATGCATAATGGCCAATTTGACACCTGTGGTTGTCCTCACCAATACCTGGCCCTGTCGCTCCTAATACCCCGAAGCATAGAGCAGGTCCTAACCGGATAA" \
         "CTCAGCTAACAGAAACTCCCCCAAGAACTAAGCACACCCAATGTGAACGTAGTCCGCTAGTGCTAGCGCTTCCTTACAGCCTTTCCTTATGGTATCTATGAGCTGGCCTAGTAT" \
         "ACAGGTTCTCCGACAACCAAGCCTCTCGCTGCGTTCGAGCACTGCCCGATGGCTTTGACGCGAGAGCGCTGGGTCTCATAATAAGATGGGGCGCTGTAGCGTAGTATCCCTCTC" \
         "GAGGGGACCCCGTAATGATGACATAGGTACATGCTGATAGAGGGGTCGACGGTCATTAATAACGTCCGGCTCGGCCACCCCTAGACTAGAGGGGAGAAGTTTCAGTATCTCTCG" \
         "TTTTGAATGGTACATATAAGCCTAAAGACGAGGGTAGGGTCACTAAAACTAAGTGAGCAACGTGCGGTACTGTCCTAGGCGGGCTTGACATTATACTCACTACGTTGGTTTCGC" \
         "GATGAGTCACAGGACTTTTCAGACCATGTGTCTGCCTCTAGGACCAATGGCTGGGTGTTGGTATACAACAGAGTCATTCATTTACGTCGTATATTCTAATACCACTCTTCACAC" \
         "GTCGAAATTTTCTGAGTTTCGACTACGCTTGTGAGCACTTCCTACTTGGTTAAGCAAGTGTGGGACGGCCTTCTTGGGCCAGGACGTAGGTTCCGCTGACAGTACAACGGAGAC" \
         "CAGAAAAGCTATTCAAGAGAGACATGGTACAGTTCTGTATGCATAAGCGTGCCCCTTAGCGCAACTGGCGTATACCGTCGATTCAGGG" \
         "AAGTTGGTACCCTCTATTTATGCCCGGATCTTGATCTCCAGACAGGGGGTAAAGGCATGGGCCAGTTACTACCCGTATTTAGGTTGTATTCCGCATCTGAAGGCGCCGTAGTGA" \
         "TAGGCGCTGAACTGAATGCATAATGGCCAATTTGACACCTGTGGTTGTCCTCACCAATACCTGGCCCTGTCGCTCCTAATACCCCGAAGCATAGAGCAGGTCCTAACCGGATAA" \
         "CTCAGCTAACAGAAACTCCCCCAAGAACTAAGCACACCCAATGTGAACGTAGTCCGCTAGTGCTAGCGCTTCCTTACAGCCTTTCCTTATGGTATCTATGAGCTGGCCTAGTAT" \
         "ACAGGTTCTCCGACAACCAAGCCTCTCGCTGCGTTCGAGCACTGCCCGATGGCTTTGACGCGAGAGCGCTGGGTCTCATAATAAGATGGGGCGCTGTAGCGTAGTATCCCTCTC" \
         "GAGGGGACCCCGTAATGATGACATAGGTACATGCTGATAGAGGGGTCGACGGTCATTAATAACGTCCGGCTCGGCCACCCCTAGACTAGAGGGGAGAAGTTTCAGTATCTCTCG" \
         "TTTTGAATGGTACATATAAGCCTAAAGACGAGGGTAGGGTCACTAAAACTAAGTGAGCAACGTGCGGTACTGTCCTAGGCGGGCTTGACATTATACTCACTACGTTGGTTTCGC" \
         "GATGAGTCACAGGACTTTTCAGACCATGTGTCTGCCTCTAGGACCAATGGCTGGGTGTTGGTATACAACAGAGTCATTCATTTACGTCGTATATTCTAATACCACTCTTCACAC" \
         "GTCGAAATTTTCTGAGTTTCGACTACGCTTGTGAGCACTTCCTACTTGGTTAAGCAAGTGTGGGACGGCCTTCTTGGGCCAGGACGTAGGTTCCGCTGACAGTACAACGGAGAC" \
         "CAGAAAAGCTATTCAAGAGAGACATGGTACAGTTCTGTATGCATAAGCGTGCCCCTTAGCGCAACTGGCGTATACCGTCGATTCAGGG" \
         "AAGTTGGTACCCTCTATTTATGCCCGGATCTTGATCTCCAGACAGGGGGTAAAGGCATGGGCCAGTTACTACCCGTATTTAGGTTGTATTCCGCATCTGAAGGCGCCGTAGTGA" \
         "TAGGCGCTGAACTGAATGCATAATGGCCAATTTGACACCTGTGGTTGTCCTCACCAATACCTGGCCCTGTCGCTCCTAATACCCCGAAGCATAGAGCAGGTCCTAACCGGATAA" \
         "CTCAGCTAACAGAAACTCCCCCAAGAACTAAGCACACCCAATGTGAACGTAGTCCGCTAGTGCTAGCGCTTCCTTACAGCCTTTCCTTATGGTATCTATGAGCTGGCCTAGTAT" \
         "ACAGGTTCTCCGACAACCAAGCCTCTCGCTGCGTTCGAGCACTGCCCGATGGCTTTGACGCGAGAGCGCTGGGTCTCATAATAAGATGGGGCGCTGTAGCGTAGTATCCCTCTC" \
         "GAGGGGACCCCGTAATGATGACATAGGTACATGCTGATAGAGGGGTCGACGGTCATTAATAACGTCCGGCTCGGCCACCCCTAGACTAGAGGGGAGAAGTTTCAGTATCTCTCG" \
         "TTTTGAATGGTACATATAAGCCTAAAGACGAGGGTAGGGTCACTAAAACTAAGTGAGCAACGTGCGGTACTGTCCTAGGCGGGCTTGACATTATACTCACTACGTTGGTTTCGC" \
         "GATGAGTCACAGGACTTTTCAGACCATGTGTCTGCCTCTAGGACCAATGGCTGGGTGTTGGTATACAACAGAGTCATTCATTTACGTCGTATATTCTAATACCACTCTTCACAC" \
         "GTCGAAATTTTCTGAGTTTCGACTACGCTTGTGAGCACTTCCTACTTGGTTAAGCAAGTGTGGGACGGCCTTCTTGGGCCAGGACGTAGGTTCCGCTGACAGTACAACGGAGAC" \
         "CAGAAAAGCTATTCAAGAGAGACATGGTACAGTTCTGTATGCATAAGCGTGCCCCTTAGCGCAACTGGCGTATACCGTCGATTCAGGG" \
         "AAGTTGGTACCCTCTATTTATGCCCGGATCTTGATCTCCAGACAGGGGGTAAAGGCATGGGCCAGTTACTACCCGTATTTAGGTTGTATTCCGCATCTGAAGGCGCCGTAGTGA" \
         "TAGGCGCTGAACTGAATGCATAATGGCCAATTTGACACCTGTGGTTGTCCTCACCAATACCTGGCCCTGTCGCTCCTAATACCCCGAAGCATAGAGCAGGTCCTAACCGGATAA" \
         "CTCAGCTAACAGAAACTCCCCCAAGAACTAAGCACACCCAATGTGAACGTAGTCCGCTAGTGCTAGCGCTTCCTTACAGCCTTTCCTTATGGTATCTATGAGCTGGCCTAGTAT" \
         "ACAGGTTCTCCGACAACCAAGCCTCTCGCTGCGTTCGAGCACTGCCCGATGGCTTTGACGCGAGAGCGCTGGGTCTCATAATAAGATGGGGCGCTGTAGCGTAGTATCCCTCTC" \
         "GAGGGGACCCCGTAATGATGACATAGGTACATGCTGATAGAGGGGTCGACGGTCATTAATAACGTCCGGCTCGGCCACCCCTAGACTAGAGGGGAGAAGTTTCAGTATCTCTCG" \
         "TTTTGAATGGTACATATAAGCCTAAAGACGAGGGTAGGGTCACTAAAACTAAGTGAGCAACGTGCGGTACTGTCCTAGGCGGGCTTGACATTATACTCACTACGTTGGTTTCGC" \
         "GATGAGTCACAGGACTTTTCAGACCATGTGTCTGCCTCTAGGACCAATGGCTGGGTGTTGGTATACAACAGAGTCATTCATTTACGTCGTATATTCTAATACCACTCTTCACAC" \
         "GTCGAAATTTTCTGAGTTTCGACTACGCTTGTGAGCACTTCCTACTTGGTTAAGCAAGTGTGGGACGGCCTTCTTGGGCCAGGACGTAGGTTCCGCTGACAGTACAACGGAGAC" \
         "CAGAAAAGCTATTCAAGAGAGACATGGTACAGTTCTGTATGCATAAGCGTGCCCCTTAGCGCAACTGGCGTATACCGTCGATTCAGGG" \
         "AAGTTGGTACCCTCTATTTATGCCCGGATCTTGATCTCCAGACAGGGGGTAAAGGCATGGGCCAGTTACTACCCGTATTTAGGTTGTATTCCGCATCTGAAGGCGCCGTAGTGA" \
         "TAGGCGCTGAACTGAATGCATAATGGCCAATTTGACACCTGTGGTTGTCCTCACCAATACCTGGCCCTGTCGCTCCTAATACCCCGAAGCATAGAGCAGGTCCTAACCGGATAA" \
         "CTCAGCTAACAGAAACTCCCCCAAGAACTAAGCACACCCAATGTGAACGTAGTCCGCTAGTGCTAGCGCTTCCTTACAGCCTTTCCTTATGGTATCTATGAGCTGGCCTAGTAT" \
         "ACAGGTTCTCCGACAACCAAGCCTCTCGCTGCGTTCGAGCACTGCCCGATGGCTTTGACGCGAGAGCGCTGGGTCTCATAATAAGATGGGGCGCTGTAGCGTAGTATCCCTCTC" \
         "GAGGGGACCCCGTAATGATGACATAGGTACATGCTGATAGAGGGGTCGACGGTCATTAATAACGTCCGGCTCGGCCACCCCTAGACTAGAGGGGAGAAGTTTCAGTATCTCTCG" \
         "TTTTGAATGGTACATATAAGCCTAAAGACGAGGGTAGGGTCACTAAAACTAAGTGAGCAACGTGCGGTACTGTCCTAGGCGGGCTTGACATTATACTCACTACGTTGGTTTCGC" \
         "GATGAGTCACAGGACTTTTCAGACCATGTGTCTGCCTCTAGGACCAATGGCTGGGTGTTGGTATACAACAGAGTCATTCATTTACGTCGTATATTCTAATACCACTCTTCACAC" \
         "GTCGAAATTTTCTGAGTTTCGACTACGCTTGTGAGCACTTCCTACTTGGTTAAGCAAGTGTGGGACGGCCTTCTTGGGCCAGGACGTAGGTTCCGCTGACAGTACAACGGAGAC" \
         "CAGAAAAGCTATTCAAGAGAGACATGGTACAGTTCTGTATGCATAAGCGTGCCCCTTAGCGCAACTGGCGTATACCGTCGATTCAGGG" \
         "AAGTTGGTACCCTCTATTTATGCCCGGATCTTGATCTCCAGACAGGGGGTAAAGGCATGGGCCAGTTACTACCCGTATTTAGGTTGTATTCCGCATCTGAAGGCGCCGTAGTGA" \
         "TAGGCGCTGAACTGAATGCATAATGGCCAATTTGACACCTGTGGTTGTCCTCACCAATACCTGGCCCTGTCGCTCCTAATACCCCGAAGCATAGAGCAGGTCCTAACCGGATAA" \
         "CTCAGCTAACAGAAACTCCCCCAAGAACTAAGCACACCCAATGTGAACGTAGTCCGCTAGTGCTAGCGCTTCCTTACAGCCTTTCCTTATGGTATCTATGAGCTGGCCTAGTAT" \
         "ACAGGTTCTCCGACAACCAAGCCTCTCGCTGCGTTCGAGCACTGCCCGATGGCTTTGACGCGAGAGCGCTGGGTCTCATAATAAGATGGGGCGCTGTAGCGTAGTATCCCTCTC" \
         "GAGGGGACCCCGTAATGATGACATAGGTACATGCTGATAGAGGGGTCGACGGTCATTAATAACGTCCGGCTCGGCCACCCCTAGACTAGAGGGGAGAAGTTTCAGTATCTCTCG" \
         "TTTTGAATGGTACATATAAGCCTAAAGACGAGGGTAGGGTCACTAAAACTAAGTGAGCAACGTGCGGTACTGTCCTAGGCGGGCTTGACATTATACTCACTACGTTGGTTTCGC" \
         "GATGAGTCACAGGACTTTTCAGACCATGTGTCTGCCTCTAGGACCAATGGCTGGGTGTTGGTATACAACAGAGTCATTCATTTACGTCGTATATTCTAATACCACTCTTCACAC" \
         "GTCGAAATTTTCTGAGTTTCGACTACGCTTGTGAGCACTTCCTACTTGGTTAAGCAAGTGTGGGACGGCCTTCTTGGGCCAGGACGTAGGTTCCGCTGACAGTACAACGGAGAC" \
         "CAGAAAAGCTATTCAAGAGAGACATGGTACAGTTCTGTATGCATAAGCGTGCCCCTTAGCGCAACTGGCGTATACCGTCGATTCAGGG" \
         "AAGTTGGTACCCTCTATTTATGCCCGGATCTTGATCTCCAGACAGGGGGTAAAGGCATGGGCCAGTTACTACCCGTATTTAGGTTGTATTCCGCATCTGAAGGCGCCGTAGTGA" \
         "TAGGCGCTGAACTGAATGCATAATGGCCAATTTGACACCTGTGGTTGTCCTCACCAATACCTGGCCCTGTCGCTCCTAATACCCCGAAGCATAGAGCAGGTCCTAACCGGATAA" \
         "CTCAGCTAACAGAAACTCCCCCAAGAACTAAGCACACCCAATGTGAACGTAGTCCGCTAGTGCTAGCGCTTCCTTACAGCCTTTCCTTATGGTATCTATGAGCTGGCCTAGTAT" \
         "ACAGGTTCTCCGACAACCAAGCCTCTCGCTGCGTTCGAGCACTGCCCGATGGCTTTGACGCGAGAGCGCTGGGTCTCATAATAAGATGGGGCGCTGTAGCGTAGTATCCCTCTC" \
         "GAGGGGACCCCGTAATGATGACATAGGTACATGCTGATAGAGGGGTCGACGGTCATTAATAACGTCCGGCTCGGCCACCCCTAGACTAGAGGGGAGAAGTTTCAGTATCTCTCG" \
         "TTTTGAATGGTACATATAAGCCTAAAGACGAGGGTAGGGTCACTAAAACTAAGTGAGCAACGTGCGGTACTGTCCTAGGCGGGCTTGACATTATACTCACTACGTTGGTTTCGC" \
         "GATGAGTCACAGGACTTTTCAGACCATGTGTCTGCCTCTAGGACCAATGGCTGGGTGTTGGTATACAACAGAGTCATTCATTTACGTCGTATATTCTAATACCACTCTTCACAC" \
         "GTCGAAATTTTCTGAGTTTCGACTACGCTTGTGAGCACTTCCTACTTGGTTAAGCAAGTGTGGGACGGCCTTCTTGGGCCAGGACGTAGGTTCCGCTGACAGTACAACGGAGAC" \
         "CAGAAAAGCTATTCAAGAGAGACATGGTACAGTTCTGTATGCATAAGCGTGCCCCTTAGCGCAACTGGCGTATACCGTCGATTCAGGG" \
         "AAGTTGGTACCCTCTATTTATGCCCGGATCTTGATCTCCAGACAGGGGGTAAAGGCATGGGCCAGTTACTACCCGTATTTAGGTTGTATTCCGCATCTGAAGGCGCCGTAGTGA" \
         "TAGGCGCTGAACTGAATGCATAATGGCCAATTTGACACCTGTGGTTGTCCTCACCAATACCTGGCCCTGTCGCTCCTAATACCCCGAAGCATAGAGCAGGTCCTAACCGGATAA" \
         "CTCAGCTAACAGAAACTCCCCCAAGAACTAAGCACACCCAATGTGAACGTAGTCCGCTAGTGCTAGCGCTTCCTTACAGCCTTTCCTTATGGTATCTATGAGCTGGCCTAGTAT" \
         "ACAGGTTCTCCGACAACCAAGCCTCTCGCTGCGTTCGAGCACTGCCCGATGGCTTTGACGCGAGAGCGCTGGGTCTCATAATAAGATGGGGCGCTGTAGCGTAGTATCCCTCTC" \
         "GAGGGGACCCCGTAATGATGACATAGGTACATGCTGATAGAGGGGTCGACGGTCATTAATAACGTCCGGCTCGGCCACCCCTAGACTAGAGGGGAGAAGTTTCAGTATCTCTCG" \
         "TTTTGAATGGTACATATAAGCCTAAAGACGAGGGTAGGGTCACTAAAACTAAGTGAGCAACGTGCGGTACTGTCCTAGGCGGGCTTGACATTATACTCACTACGTTGGTTTCGC" \
         "GATGAGTCACAGGACTTTTCAGACCATGTGTCTGCCTCTAGGACCAATGGCTGGGTGTTGGTATACAACAGAGTCATTCATTTACGTCGTATATTCTAATACCACTCTTCACAC" \
         "GTCGAAATTTTCTGAGTTTCGACTACGCTTGTGAGCACTTCCTACTTGGTTAAGCAAGTGTGGGACGGCCTTCTTGGGCCAGGACGTAGGTTCCGCTGACAGTACAACGGAGAC" \
         "CAGAAAAGCTATTCAAGAGAGACATGGTACAGTTCTGTATGCATAAGCGTGCCCCTTAGCGCAACTGGCGTATACCGTCGATTCAGGG" \
         "AAGTTGGTACCCTCTATTTATGCCCGGATCTTGATCTCCAGACAGGGGGTAAAGGCATGGGCCAGTTACTACCCGTATTTAGGTTGTATTCCGCATCTGAAGGCGCCGTAGTGA" \
         "TAGGCGCTGAACTGAATGCATAATGGCCAATTTGACACCTGTGGTTGTCCTCACCAATACCTGGCCCTGTCGCTCCTAATACCCCGAAGCATAGAGCAGGTCCTAACCGGATAA" \
         "CTCAGCTAACAGAAACTCCCCCAAGAACTAAGCACACCCAATGTGAACGTAGTCCGCTAGTGCTAGCGCTTCCTTACAGCCTTTCCTTATGGTATCTATGAGCTGGCCTAGTAT" \
         "ACAGGTTCTCCGACAACCAAGCCTCTCGCTGCGTTCGAGCACTGCCCGATGGCTTTGACGCGAGAGCGCTGGGTCTCATAATAAGATGGGGCGCTGTAGCGTAGTATCCCTCTC" \
         "GAGGGGACCCCGTAATGATGACATAGGTACATGCTGATAGAGGGGTCGACGGTCATTAATAACGTCCGGCTCGGCCACCCCTAGACTAGAGGGGAGAAGTTTCAGTATCTCTCG" \
         "TTTTGAATGGTACATATAAGCCTAAAGACGAGGGTAGGGTCACTAAAACTAAGTGAGCAACGTGCGGTACTGTCCTAGGCGGGCTTGACATTATACTCACTACGTTGGTTTCGC" \
         "GATGAGTCACAGGACTTTTCAGACCATGTGTCTGCCTCTAGGACCAATGGCTGGGTGTTGGTATACAACAGAGTCATTCATTTACGTCGTATATTCTAATACCACTCTTCACAC" \
         "GTCGAAATTTTCTGAGTTTCGACTACGCTTGTGAGCACTTCCTACTTGGTTAAGCAAGTGTGGGACGGCCTTCTTGGGCCAGGACGTAGGTTCCGCTGACAGTACAACGGAGAC" \
         "CAGAAAAGCTATTCAAGAGAGACATGGTACAGTTCTGTATGCATAAGCGTGCCCCTTAGCGCAACTGGCGTATACCGTCGATTCAGGG"

b10000 = 'GTTCGTTCATGACTGTCTAAACCTATTCGACGTGCGCCCTTTAGAGGATCATTCTAGATT' \
         'GTATGAGACCGATAAGATGAACATTTTATCAATTCCGCGCGGGGCTACAATATGATCTTG' \
         'ATAATTGTGGTATAAGAGACGATAAAGGCGATTTTCTATCAATCCATCTGACAAACCGTC' \
         'TCTAGCATCAATGCAACGCGTTTGGTTGGCCTAGTGGCGTTAGTGAATGGGGACCAGTTC' \
         'AGTATCGCCCATCGGACTTGAACAATAAGCGTGAACGGACCCAAACTTTTATGCCCGGCC' \
         'GGTTTCGACCCCGTTGCGACGAGTTATCATTTCAGCACGAGGACATGGTCCCGGTTTGAG' \
         'ACTCGTAAAACCCTACCTAGCACGGTATTCCGGACACTAATATAAAATGAATACCTGCGA' \
         'TAATAGATCAAGCGCTACAGCCCGGGCCCAGCTACCCGGATATAAATCTAAATGTTGCAT' \
         'AAACCATTATTGTACCTCAACTTGAGTTCGATAGGCCGCGCACTGTGGCTTTGCCATGCC' \
         'TACGCTTCACCATAGACTACACGTGAAAATTCGCATTAGCCTACACGACACGCCCGAGTC' \
         'TAAATGTTCCTCGAAGAACAATGTTGCCAAAGTTCTATTGATTACACACAAGCGCACTAA' \
         'AAGACAAAATTTATGGCCAGGGGCGGTAGTAGAATAGCAAGGTGAGTTGTTCGCAGGCTA' \
         'CATGCGATGCGATAGTATACTCGCGACCGGAGGGGGTCCCACACCCTTATGCTGATATTG' \
         'CTTATGCATATGGCTACGATACAGCCGAAACCAAACGGCTAAATATTAGTACCTAGTTTC' \
         'GAAAACATGGCTTGCGCATCACCTTCCATAAGGACGACGTCGAGCCAAGCGCATAGAAGG' \
         'CTTTATAATTATAAGGACAATGGGGACATCTCGTCCTGGTGTATTCGTCCAAGTGCTTGG' \
         'TGAAATCATCACGACCCATAGATGCTTCATCAGCATCATC' \
         'GTTCGTTCATGACTGTCTAAACCTATTCGACGTGCGCCCTTTAGAGGATCATTCTAGATT' \
         'GTATGAGACCGATAAGATGAACATTTTATCAATTCCGCGCGGGGCTACAATATGATCTTG' \
         'ATAATTGTGGTATAAGAGACGATAAAGGCGATTTTCTATCAATCCATCTGACAAACCGTC' \
         'TCTAGCATCAATGCAACGCGTTTGGTTGGCCTAGTGGCGTTAGTGAATGGGGACCAGTTC' \
         'AGTATCGCCCATCGGACTTGAACAATAAGCGTGAACGGACCCAAACTTTTATGCCCGGCC' \
         'GGTTTCGACCCCGTTGCGACGAGTTATCATTTCAGCACGAGGACATGGTCCCGGTTTGAG' \
         'ACTCGTAAAACCCTACCTAGCACGGTATTCCGGACACTAATATAAAATGAATACCTGCGA' \
         'TAATAGATCAAGCGCTACAGCCCGGGCCCAGCTACCCGGATATAAATCTAAATGTTGCAT' \
         'AAACCATTATTGTACCTCAACTTGAGTTCGATAGGCCGCGCACTGTGGCTTTGCCATGCC' \
         'TACGCTTCACCATAGACTACACGTGAAAATTCGCATTAGCCTACACGACACGCCCGAGTC' \
         'TAAATGTTCCTCGAAGAACAATGTTGCCAAAGTTCTATTGATTACACACAAGCGCACTAA' \
         'AAGACAAAATTTATGGCCAGGGGCGGTAGTAGAATAGCAAGGTGAGTTGTTCGCAGGCTA' \
         'CATGCGATGCGATAGTATACTCGCGACCGGAGGGGGTCCCACACCCTTATGCTGATATTG' \
         'CTTATGCATATGGCTACGATACAGCCGAAACCAAACGGCTAAATATTAGTACCTAGTTTC' \
         'GAAAACATGGCTTGCGCATCACCTTCCATAAGGACGACGTCGAGCCAAGCGCATAGAAGG' \
         'CTTTATAATTATAAGGACAATGGGGACATCTCGTCCTGGTGTATTCGTCCAAGTGCTTGG' \
         'TGAAATCATCACGACCCATAGATGCTTCATCAGCATCATC' \
         'GTTCGTTCATGACTGTCTAAACCTATTCGACGTGCGCCCTTTAGAGGATCATTCTAGATT' \
         'GTATGAGACCGATAAGATGAACATTTTATCAATTCCGCGCGGGGCTACAATATGATCTTG' \
         'ATAATTGTGGTATAAGAGACGATAAAGGCGATTTTCTATCAATCCATCTGACAAACCGTC' \
         'TCTAGCATCAATGCAACGCGTTTGGTTGGCCTAGTGGCGTTAGTGAATGGGGACCAGTTC' \
         'AGTATCGCCCATCGGACTTGAACAATAAGCGTGAACGGACCCAAACTTTTATGCCCGGCC' \
         'GGTTTCGACCCCGTTGCGACGAGTTATCATTTCAGCACGAGGACATGGTCCCGGTTTGAG' \
         'ACTCGTAAAACCCTACCTAGCACGGTATTCCGGACACTAATATAAAATGAATACCTGCGA' \
         'TAATAGATCAAGCGCTACAGCCCGGGCCCAGCTACCCGGATATAAATCTAAATGTTGCAT' \
         'AAACCATTATTGTACCTCAACTTGAGTTCGATAGGCCGCGCACTGTGGCTTTGCCATGCC' \
         'TACGCTTCACCATAGACTACACGTGAAAATTCGCATTAGCCTACACGACACGCCCGAGTC' \
         'TAAATGTTCCTCGAAGAACAATGTTGCCAAAGTTCTATTGATTACACACAAGCGCACTAA' \
         'AAGACAAAATTTATGGCCAGGGGCGGTAGTAGAATAGCAAGGTGAGTTGTTCGCAGGCTA' \
         'CATGCGATGCGATAGTATACTCGCGACCGGAGGGGGTCCCACACCCTTATGCTGATATTG' \
         'CTTATGCATATGGCTACGATACAGCCGAAACCAAACGGCTAAATATTAGTACCTAGTTTC' \
         'GAAAACATGGCTTGCGCATCACCTTCCATAAGGACGACGTCGAGCCAAGCGCATAGAAGG' \
         'CTTTATAATTATAAGGACAATGGGGACATCTCGTCCTGGTGTATTCGTCCAAGTGCTTGG' \
         'TGAAATCATCACGACCCATAGATGCTTCATCAGCATCATC' \
         'GTTCGTTCATGACTGTCTAAACCTATTCGACGTGCGCCCTTTAGAGGATCATTCTAGATT' \
         'GTATGAGACCGATAAGATGAACATTTTATCAATTCCGCGCGGGGCTACAATATGATCTTG' \
         'ATAATTGTGGTATAAGAGACGATAAAGGCGATTTTCTATCAATCCATCTGACAAACCGTC' \
         'TCTAGCATCAATGCAACGCGTTTGGTTGGCCTAGTGGCGTTAGTGAATGGGGACCAGTTC' \
         'AGTATCGCCCATCGGACTTGAACAATAAGCGTGAACGGACCCAAACTTTTATGCCCGGCC' \
         'GGTTTCGACCCCGTTGCGACGAGTTATCATTTCAGCACGAGGACATGGTCCCGGTTTGAG' \
         'ACTCGTAAAACCCTACCTAGCACGGTATTCCGGACACTAATATAAAATGAATACCTGCGA' \
         'TAATAGATCAAGCGCTACAGCCCGGGCCCAGCTACCCGGATATAAATCTAAATGTTGCAT' \
         'AAACCATTATTGTACCTCAACTTGAGTTCGATAGGCCGCGCACTGTGGCTTTGCCATGCC' \
         'TACGCTTCACCATAGACTACACGTGAAAATTCGCATTAGCCTACACGACACGCCCGAGTC' \
         'TAAATGTTCCTCGAAGAACAATGTTGCCAAAGTTCTATTGATTACACACAAGCGCACTAA' \
         'AAGACAAAATTTATGGCCAGGGGCGGTAGTAGAATAGCAAGGTGAGTTGTTCGCAGGCTA' \
         'CATGCGATGCGATAGTATACTCGCGACCGGAGGGGGTCCCACACCCTTATGCTGATATTG' \
         'CTTATGCATATGGCTACGATACAGCCGAAACCAAACGGCTAAATATTAGTACCTAGTTTC' \
         'GAAAACATGGCTTGCGCATCACCTTCCATAAGGACGACGTCGAGCCAAGCGCATAGAAGG' \
         'CTTTATAATTATAAGGACAATGGGGACATCTCGTCCTGGTGTATTCGTCCAAGTGCTTGG' \
         'TGAAATCATCACGACCCATAGATGCTTCATCAGCATCATC' \
         'GTTCGTTCATGACTGTCTAAACCTATTCGACGTGCGCCCTTTAGAGGATCATTCTAGATT' \
         'GTATGAGACCGATAAGATGAACATTTTATCAATTCCGCGCGGGGCTACAATATGATCTTG' \
         'ATAATTGTGGTATAAGAGACGATAAAGGCGATTTTCTATCAATCCATCTGACAAACCGTC' \
         'TCTAGCATCAATGCAACGCGTTTGGTTGGCCTAGTGGCGTTAGTGAATGGGGACCAGTTC' \
         'AGTATCGCCCATCGGACTTGAACAATAAGCGTGAACGGACCCAAACTTTTATGCCCGGCC' \
         'GGTTTCGACCCCGTTGCGACGAGTTATCATTTCAGCACGAGGACATGGTCCCGGTTTGAG' \
         'ACTCGTAAAACCCTACCTAGCACGGTATTCCGGACACTAATATAAAATGAATACCTGCGA' \
         'TAATAGATCAAGCGCTACAGCCCGGGCCCAGCTACCCGGATATAAATCTAAATGTTGCAT' \
         'AAACCATTATTGTACCTCAACTTGAGTTCGATAGGCCGCGCACTGTGGCTTTGCCATGCC' \
         'TACGCTTCACCATAGACTACACGTGAAAATTCGCATTAGCCTACACGACACGCCCGAGTC' \
         'TAAATGTTCCTCGAAGAACAATGTTGCCAAAGTTCTATTGATTACACACAAGCGCACTAA' \
         'AAGACAAAATTTATGGCCAGGGGCGGTAGTAGAATAGCAAGGTGAGTTGTTCGCAGGCTA' \
         'CATGCGATGCGATAGTATACTCGCGACCGGAGGGGGTCCCACACCCTTATGCTGATATTG' \
         'CTTATGCATATGGCTACGATACAGCCGAAACCAAACGGCTAAATATTAGTACCTAGTTTC' \
         'GAAAACATGGCTTGCGCATCACCTTCCATAAGGACGACGTCGAGCCAAGCGCATAGAAGG' \
         'CTTTATAATTATAAGGACAATGGGGACATCTCGTCCTGGTGTATTCGTCCAAGTGCTTGG' \
         'TGAAATCATCACGACCCATAGATGCTTCATCAGCATCATC' \
         'GTTCGTTCATGACTGTCTAAACCTATTCGACGTGCGCCCTTTAGAGGATCATTCTAGATT' \
         'GTATGAGACCGATAAGATGAACATTTTATCAATTCCGCGCGGGGCTACAATATGATCTTG' \
         'ATAATTGTGGTATAAGAGACGATAAAGGCGATTTTCTATCAATCCATCTGACAAACCGTC' \
         'TCTAGCATCAATGCAACGCGTTTGGTTGGCCTAGTGGCGTTAGTGAATGGGGACCAGTTC' \
         'AGTATCGCCCATCGGACTTGAACAATAAGCGTGAACGGACCCAAACTTTTATGCCCGGCC' \
         'GGTTTCGACCCCGTTGCGACGAGTTATCATTTCAGCACGAGGACATGGTCCCGGTTTGAG' \
         'ACTCGTAAAACCCTACCTAGCACGGTATTCCGGACACTAATATAAAATGAATACCTGCGA' \
         'TAATAGATCAAGCGCTACAGCCCGGGCCCAGCTACCCGGATATAAATCTAAATGTTGCAT' \
         'AAACCATTATTGTACCTCAACTTGAGTTCGATAGGCCGCGCACTGTGGCTTTGCCATGCC' \
         'TACGCTTCACCATAGACTACACGTGAAAATTCGCATTAGCCTACACGACACGCCCGAGTC' \
         'TAAATGTTCCTCGAAGAACAATGTTGCCAAAGTTCTATTGATTACACACAAGCGCACTAA' \
         'AAGACAAAATTTATGGCCAGGGGCGGTAGTAGAATAGCAAGGTGAGTTGTTCGCAGGCTA' \
         'CATGCGATGCGATAGTATACTCGCGACCGGAGGGGGTCCCACACCCTTATGCTGATATTG' \
         'CTTATGCATATGGCTACGATACAGCCGAAACCAAACGGCTAAATATTAGTACCTAGTTTC' \
         'GAAAACATGGCTTGCGCATCACCTTCCATAAGGACGACGTCGAGCCAAGCGCATAGAAGG' \
         'CTTTATAATTATAAGGACAATGGGGACATCTCGTCCTGGTGTATTCGTCCAAGTGCTTGG' \
         'TGAAATCATCACGACCCATAGATGCTTCATCAGCATCATC' \
         'GTTCGTTCATGACTGTCTAAACCTATTCGACGTGCGCCCTTTAGAGGATCATTCTAGATT' \
         'GTATGAGACCGATAAGATGAACATTTTATCAATTCCGCGCGGGGCTACAATATGATCTTG' \
         'ATAATTGTGGTATAAGAGACGATAAAGGCGATTTTCTATCAATCCATCTGACAAACCGTC' \
         'TCTAGCATCAATGCAACGCGTTTGGTTGGCCTAGTGGCGTTAGTGAATGGGGACCAGTTC' \
         'AGTATCGCCCATCGGACTTGAACAATAAGCGTGAACGGACCCAAACTTTTATGCCCGGCC' \
         'GGTTTCGACCCCGTTGCGACGAGTTATCATTTCAGCACGAGGACATGGTCCCGGTTTGAG' \
         'ACTCGTAAAACCCTACCTAGCACGGTATTCCGGACACTAATATAAAATGAATACCTGCGA' \
         'TAATAGATCAAGCGCTACAGCCCGGGCCCAGCTACCCGGATATAAATCTAAATGTTGCAT' \
         'AAACCATTATTGTACCTCAACTTGAGTTCGATAGGCCGCGCACTGTGGCTTTGCCATGCC' \
         'TACGCTTCACCATAGACTACACGTGAAAATTCGCATTAGCCTACACGACACGCCCGAGTC' \
         'TAAATGTTCCTCGAAGAACAATGTTGCCAAAGTTCTATTGATTACACACAAGCGCACTAA' \
         'AAGACAAAATTTATGGCCAGGGGCGGTAGTAGAATAGCAAGGTGAGTTGTTCGCAGGCTA' \
         'CATGCGATGCGATAGTATACTCGCGACCGGAGGGGGTCCCACACCCTTATGCTGATATTG' \
         'CTTATGCATATGGCTACGATACAGCCGAAACCAAACGGCTAAATATTAGTACCTAGTTTC' \
         'GAAAACATGGCTTGCGCATCACCTTCCATAAGGACGACGTCGAGCCAAGCGCATAGAAGG' \
         'CTTTATAATTATAAGGACAATGGGGACATCTCGTCCTGGTGTATTCGTCCAAGTGCTTGG' \
         'TGAAATCATCACGACCCATAGATGCTTCATCAGCATCATC' \
         'GTTCGTTCATGACTGTCTAAACCTATTCGACGTGCGCCCTTTAGAGGATCATTCTAGATT' \
         'GTATGAGACCGATAAGATGAACATTTTATCAATTCCGCGCGGGGCTACAATATGATCTTG' \
         'ATAATTGTGGTATAAGAGACGATAAAGGCGATTTTCTATCAATCCATCTGACAAACCGTC' \
         'TCTAGCATCAATGCAACGCGTTTGGTTGGCCTAGTGGCGTTAGTGAATGGGGACCAGTTC' \
         'AGTATCGCCCATCGGACTTGAACAATAAGCGTGAACGGACCCAAACTTTTATGCCCGGCC' \
         'GGTTTCGACCCCGTTGCGACGAGTTATCATTTCAGCACGAGGACATGGTCCCGGTTTGAG' \
         'ACTCGTAAAACCCTACCTAGCACGGTATTCCGGACACTAATATAAAATGAATACCTGCGA' \
         'TAATAGATCAAGCGCTACAGCCCGGGCCCAGCTACCCGGATATAAATCTAAATGTTGCAT' \
         'AAACCATTATTGTACCTCAACTTGAGTTCGATAGGCCGCGCACTGTGGCTTTGCCATGCC' \
         'TACGCTTCACCATAGACTACACGTGAAAATTCGCATTAGCCTACACGACACGCCCGAGTC' \
         'TAAATGTTCCTCGAAGAACAATGTTGCCAAAGTTCTATTGATTACACACAAGCGCACTAA' \
         'AAGACAAAATTTATGGCCAGGGGCGGTAGTAGAATAGCAAGGTGAGTTGTTCGCAGGCTA' \
         'CATGCGATGCGATAGTATACTCGCGACCGGAGGGGGTCCCACACCCTTATGCTGATATTG' \
         'CTTATGCATATGGCTACGATACAGCCGAAACCAAACGGCTAAATATTAGTACCTAGTTTC' \
         'GAAAACATGGCTTGCGCATCACCTTCCATAAGGACGACGTCGAGCCAAGCGCATAGAAGG' \
         'CTTTATAATTATAAGGACAATGGGGACATCTCGTCCTGGTGTATTCGTCCAAGTGCTTGG' \
         'TGAAATCATCACGACCCATAGATGCTTCATCAGCATCATC' \
         'GTTCGTTCATGACTGTCTAAACCTATTCGACGTGCGCCCTTTAGAGGATCATTCTAGATT' \
         'GTATGAGACCGATAAGATGAACATTTTATCAATTCCGCGCGGGGCTACAATATGATCTTG' \
         'ATAATTGTGGTATAAGAGACGATAAAGGCGATTTTCTATCAATCCATCTGACAAACCGTC' \
         'TCTAGCATCAATGCAACGCGTTTGGTTGGCCTAGTGGCGTTAGTGAATGGGGACCAGTTC' \
         'AGTATCGCCCATCGGACTTGAACAATAAGCGTGAACGGACCCAAACTTTTATGCCCGGCC' \
         'GGTTTCGACCCCGTTGCGACGAGTTATCATTTCAGCACGAGGACATGGTCCCGGTTTGAG' \
         'ACTCGTAAAACCCTACCTAGCACGGTATTCCGGACACTAATATAAAATGAATACCTGCGA' \
         'TAATAGATCAAGCGCTACAGCCCGGGCCCAGCTACCCGGATATAAATCTAAATGTTGCAT' \
         'AAACCATTATTGTACCTCAACTTGAGTTCGATAGGCCGCGCACTGTGGCTTTGCCATGCC' \
         'TACGCTTCACCATAGACTACACGTGAAAATTCGCATTAGCCTACACGACACGCCCGAGTC' \
         'TAAATGTTCCTCGAAGAACAATGTTGCCAAAGTTCTATTGATTACACACAAGCGCACTAA' \
         'AAGACAAAATTTATGGCCAGGGGCGGTAGTAGAATAGCAAGGTGAGTTGTTCGCAGGCTA' \
         'CATGCGATGCGATAGTATACTCGCGACCGGAGGGGGTCCCACACCCTTATGCTGATATTG' \
         'CTTATGCATATGGCTACGATACAGCCGAAACCAAACGGCTAAATATTAGTACCTAGTTTC' \
         'GAAAACATGGCTTGCGCATCACCTTCCATAAGGACGACGTCGAGCCAAGCGCATAGAAGG' \
         'CTTTATAATTATAAGGACAATGGGGACATCTCGTCCTGGTGTATTCGTCCAAGTGCTTGG' \
         'TGAAATCATCACGACCCATAGATGCTTCATCAGCATCATC' \
         'GTTCGTTCATGACTGTCTAAACCTATTCGACGTGCGCCCTTTAGAGGATCATTCTAGATT' \
         'GTATGAGACCGATAAGATGAACATTTTATCAATTCCGCGCGGGGCTACAATATGATCTTG' \
         'ATAATTGTGGTATAAGAGACGATAAAGGCGATTTTCTATCAATCCATCTGACAAACCGTC' \
         'TCTAGCATCAATGCAACGCGTTTGGTTGGCCTAGTGGCGTTAGTGAATGGGGACCAGTTC' \
         'AGTATCGCCCATCGGACTTGAACAATAAGCGTGAACGGACCCAAACTTTTATGCCCGGCC' \
         'GGTTTCGACCCCGTTGCGACGAGTTATCATTTCAGCACGAGGACATGGTCCCGGTTTGAG' \
         'ACTCGTAAAACCCTACCTAGCACGGTATTCCGGACACTAATATAAAATGAATACCTGCGA' \
         'TAATAGATCAAGCGCTACAGCCCGGGCCCAGCTACCCGGATATAAATCTAAATGTTGCAT' \
         'AAACCATTATTGTACCTCAACTTGAGTTCGATAGGCCGCGCACTGTGGCTTTGCCATGCC' \
         'TACGCTTCACCATAGACTACACGTGAAAATTCGCATTAGCCTACACGACACGCCCGAGTC' \
         'TAAATGTTCCTCGAAGAACAATGTTGCCAAAGTTCTATTGATTACACACAAGCGCACTAA' \
         'AAGACAAAATTTATGGCCAGGGGCGGTAGTAGAATAGCAAGGTGAGTTGTTCGCAGGCTA' \
         'CATGCGATGCGATAGTATACTCGCGACCGGAGGGGGTCCCACACCCTTATGCTGATATTG' \
         'CTTATGCATATGGCTACGATACAGCCGAAACCAAACGGCTAAATATTAGTACCTAGTTTC' \
         'GAAAACATGGCTTGCGCATCACCTTCCATAAGGACGACGTCGAGCCAAGCGCATAGAAGG' \
         'CTTTATAATTATAAGGACAATGGGGACATCTCGTCCTGGTGTATTCGTCCAAGTGCTTGG' \
         'TGAAATCATCACGACCCATAGATGCTTCATCAGCATCATC'


'''
**OUTPUT**
C:\Python34\python.exe C:/Users/Carl-Admin/Documents/PyCharm/DNA/DNA.py
Size = 10 brute:
GCCGT  is the match
5
0.009006023406982422  seconds elapsed

Size = 10 Dynamic:
GCCGT  is the match
5 is longest substring
0.0  seconds elapsed

Size = 15 brute:
ATTAGATATTGC  is the match
11
0.40827083587646484  seconds elapsed

Size = 15 Dynamic:
ATTAGATATTG  is the match
11 is longest substring
0.001001119613647461  seconds elapsed

Size = 20 brute:
GAAGGAGTTA  is the match
10
17.784836053848267  seconds elapsed

Size = 20 Dynamic:
GAAGGAGTTA  is the match
10 is longest substring
0.0  seconds elapsed

Size = 100 Dynamic:
GGGTTCGCCCCGGATCTGTTACAGCAAAGTCTGTAGCAGCTAATTAGGGCGTGTGTCAGGCTGA  is the match
64 is longest substring
0.010006904602050781  seconds elapsed

Size = 1000 Dynamic:
GTTGTTCATGACTGTCTCCAGACGGGTAAGGATCCAGTTATACCGATAGGTTTATTCCGCCGGGGCCTATGATCTGATAATGATAAGAGACATGGGTTTTCACAATCCTGCCCGTCTCTAATCAAGCAAGCGGTCCTAGGATAATCAGTCAGATCCCCAAGAACTAAGCACACCCAAACTATCCCGGCCGTTTCGCCCCGTTCGACGAGTTACATTTCGACAACAGTCCCGGTTGAGACTGCCCATGCTTTCCGGACCTTATAAAAGATCCTGCGTATATCCCTCAGGGGCCCGTAATATAAATCATGTGATAAACCATTATACTCCGGTCGACCCGACTGGGGAGAGTTCAATCTCCGTGAATTCATTAGCCTAAGACAGGGTAGTCCTAAAACAATGGCAAGTCTATGTCCACGGCTGACATTTATCCAGGGGCGTGAGTACAGGATTTTCGCAGGTCTGCTCTAGAATGGCGGGGGGTCAACAGGTATTCTTATGATATCTAATACACCACACGGAAATTTTCTAGTTTCGAACGCTTGGACACTTCCATAAGGACGCTCGGCCAACGTAGGGCTAATAAAGGACAAGCATTCGCTGGTACGTTCTGTATCATACGCCCTAGATGCTTCTCGATCA  is the match
639 is longest substring
0.9476280212402344  seconds elapsed

Process finished with exit code 0

'''
