'''
This project shows three different approaches to finding the longest common
substring (LCS). The LCS is the longest series of characters which is
present in order in both strings. LCS is useful in biology, where it can
be used to compare the similarity of two different gene sequences.

Both the brute force and dynamic run in exponential time, whereas the
dynamic approach runs in O(n^2) time, which means it is dramatically
faster for even medium length strings.

The brute force approach creates a substring of one string and checks if it is
present in the other string. It begins with the largest possible string, which
means that it can be somewhat faster than the recursive if both strings have a
large number of values in common because it checks the longest combination
and works back from there.

The recursive function recursive searches through a two dimentional matrix to find
the best possible selection of characters. This approach is inefficient because it
results in re-calculating the same values over and over again.

The dynamic programming approach is similar to the recursive, but builds up values
from the start which reduces the runtime to O(n^2)
'''

import time
import itertools

__author__ = 'Carl Rodriguez'


def lcs_dyn(a, b):
    m = len(a)
    n = len(b)

    myArr = [[0 for _ in range(m + 1)] for _ in range(n + 1)]
    myArr2 = [[0 for _ in range(m + 1)] for _ in range(n + 1)]

    big_problem = False
    for i in range(1, m + 1):
        if i % 100 == 0:
            if not big_problem:
                big_problem = True
                print("Hundreds of characters: ",end="")

            print(".",end="")
        for j in range(1, n + 1):
            if b[j - 1] == a[i - 1]:
                myArr[i][j] = myArr[i - 1][j - 1] + 1
                myArr2[i][j] = 2
            elif myArr[i][j - 1] >= myArr[i - 1][j]:
                myArr[i][j] = myArr[i][j - 1]
                myArr2[i][j] = 1
            else:
                myArr[i][j] = myArr[i - 1][j]
                myArr2[i][j] = 0
    if big_problem:
        print(" Done!")

    x = m
    y = n
    answer = ""

    while x > 0 and y > 0:
        if myArr2[x][y] == 2:
            answer = a[x - 1] + answer
            x -= 1
            y -= 1
        elif myArr2[x][y] == 1:
            y -= 1
        else:
            x -= 1

    return (myArr[i][j], answer)


def lcs_rec(a, b):
    recursions = 0
    a = lcs_rec2(a, b, len(a) - 1, len(b) - 1)
    return a


def lcs_rec2(a, b, i , j,):

    if i < 0 or j < 0:
        return (0,"")
    if a[i] == b[j]:
        recurse = lcs_rec2(a, b, i - 1, j - 1)
        return (recurse[0]+1,recurse[1]+a[i])
    else:
        left = lcs_rec2(a, b, i - 1, j)
        up = lcs_rec2(a, b, i, j - 1)
        return left if left[0] > up[0] else up



def lcs_brute(a, b):
    for i in reversed(range(len(b))):
        combos = itertools.combinations(b,i)
        for combo in combos:
            length = match(combo,a)
            if length > 0:
                return (length, ''.join(combo))


def match(sub, string):
    track = 0
    if len(sub) == 0 or len(sub) > len(string):
        return 0
    for elem in string:
        if sub[track] == elem:
            track += 1
            if track == len(sub):
                return track

    return 0 if track < len(sub) else track


def printArr(multi):
    for j in range(0, len(multi[0])):
        for i in range(0, len(multi)):
            print(multi[i][j], end=" ")
        print()


def run_test(a,b,algorith):
    types = {0:("Brute",lcs_brute),1:("Recursive",lcs_rec),2:("Dynamic",lcs_dyn)}
    run = types.get(algorith)
    if run:
        print("Running LCS",run[0],"on size",len(a),"by",len(b))
        before = time.time()
        res = run[1](a,b)
        after = time.time()
        print("The solution with a length of",res[0],"is",res[1])
        print("Time elapsed is",after-before)
        print()
        return res
    else:
        print("Algorithm not found")


a10 = "TGTTTCCCGT"
b10 = "GCTCGCATTA"

a15 = "GATTTAGATTATTGC"
b15 = "AGGTCTAGAATATTG"

a20 = "CCGCTTCTTAAGGGAGTATA"
b20 = "GGATAGACGATCGTCTCAAA"

a100 = "TGTGTGACTTCCTGGCTACTACCCGTTGCATCTAGTTACAGGTATCACTAACGTCTGATTATGCAGCTCCCAATTAGGGCCGTGTGTCAGGACTTTTTGA"
b100 = "CGGGTTCGCCCGCGGGAGTAACTGTTACAGCAAAGTACTGTACCGCAACGCTGGGGATGATATGTACGGGGCTTGTGTGATTAGACAGGGCCTGAGCTCC"

# IF long_run is set to false, the execution will skip the lcs calls
# that take longer to run
long_run = False

run_test(a10,b10,0)
run_test(a10,b10,1)
run_test(a10,b10,2)

run_test(a15,b15,0)
run_test(a15,b15,1)
run_test(a15,b15,2)


run_test(a20,b20,0)
if long_run:
    run_test(a20,b20,1)
run_test(a20,b20,2)

run_test(a100,b100,2)



a1000 = "AAGTTGGTACCCTCTATTTATGCCCGGATCTTGATCTCCAGACAGGGGGTAAAGGCATGGGCCAGTTACTACCCGTATTTAGGTTGTATTCCGCATCTGAAGGCGCCGTAGTGA" \
        "TAGGCGCTGAACTGAATGCATAATGGCCAATTTGACACCTGTGGTTGTCCTCACCAATACCTGGCCCTGTCGCTCCTAATACCCCGAAGCATAGAGCAGGTCCTAACCGGATAA" \
        "CTCAGCTAACAGAAACTCCCCCAAGAACTAAGCACACCCAATGTGAACGTAGTCCGCTAGTGCTAGCGCTTCCTTACAGCCTTTCCTTATGGTATCTATGAGCTGGCCTAGTAT" \
        "ACAGGTTCTCCGACAACCAAGCCTCTCGCTGCGTTCGAGCACTGCCCGATGGCTTTGACGCGAGAGCGCTGGGTCTCATAATAAGATGGGGCGCTGTAGCGTAGTATCCCTCTC" \
        "GAGGGGACCCCGTAATGATGACATAGGTACATGCTGATAGAGGGGTCGACGGTCATTAATAACGTCCGGCTCGGCCACCCCTAGACTAGAGGGGAGAAGTTTCAGTATCTCTCG" \
        "TTTTGAATGGTACATATAAGCCTAAAGACGAGGGTAGGGTCACTAAAACTAAGTGAGCAACGTGCGGTACTGTCCTAGGCGGGCTTGACATTATACTCACTACGTTGGTTTCGC" \
        "GATGAGTCACAGGACTTTTCAGACCATGTGTCTGCCTCTAGGACCAATGGCTGGGTGTTGGTATACAACAGAGTCATTCATTTACGTCGTATATTCTAATACCACTCTTCACAC" \
        "GTCGAAATTTTCTGAGTTTCGACTACGCTTGTGAGCACTTCCTACTTGGTTAAGCAAGTGTGGGACGGCCTTCTTGGGCCAGGACGTAGGTTCCGCTGACAGTACAACGGAGAC" \
        "CAGAAAAGCTATTCAAGAGAGACATGGTACAGTTCTGTATGCATAAGCGTGCCCCTTAGCGCAACTGGCGTATACCGTCGATTCAGGG"
b1000 = 'GTTCGTTCATGACTGTCTAAACCTATTCGACGTGCGCCCTTTAGAGGATCATTCTAGATT' \
        'GTATGAGACCGATAAGATGAACATTTTATCAATTCCGCGCGGGGCTACAATATGATCTTG' \
        'ATAATTGTGGTATAAGAGACGATAAAGGCGATTTTCTATCAATCCATCTGACAAACCGTC' \
        'TCTAGCATCAATGCAACGCGTTTGGTTGGCCTAGTGGCGTTAGTGAATGGGGACCAGTTC' \
        'AGTATCGCCCATCGGACTTGAACAATAAGCGTGAACGGACCCAAACTTTTATGCCCGGCC' \
        'GGTTTCGACCCCGTTGCGACGAGTTATCATTTCAGCACGAGGACATGGTCCCGGTTTGAG' \
        'ACTCGTAAAACCCTACCTAGCACGGTATTCCGGACACTAATATAAAATGAATACCTGCGA' \
        'TAATAGATCAAGCGCTACAGCCCGGGCCCAGCTACCCGGATATAAATCTAAATGTTGCAT' \
        'AAACCATTATTGTACCTCAACTTGAGTTCGATAGGCCGCGCACTGTGGCTTTGCCATGCC' \
        'TACGCTTCACCATAGACTACACGTGAAAATTCGCATTAGCCTACACGACACGCCCGAGTC' \
        'TAAATGTTCCTCGAAGAACAATGTTGCCAAAGTTCTATTGATTACACACAAGCGCACTAA' \
        'AAGACAAAATTTATGGCCAGGGGCGGTAGTAGAATAGCAAGGTGAGTTGTTCGCAGGCTA' \
        'CATGCGATGCGATAGTATACTCGCGACCGGAGGGGGTCCCACACCCTTATGCTGATATTG' \
        'CTTATGCATATGGCTACGATACAGCCGAAACCAAACGGCTAAATATTAGTACCTAGTTTC' \
        'GAAAACATGGCTTGCGCATCACCTTCCATAAGGACGACGTCGAGCCAAGCGCATAGAAGG' \
        'CTTTATAATTATAAGGACAATGGGGACATCTCGTCCTGGTGTATTCGTCCAAGTGCTTGG' \
        'TGAAATCATCACGACCCATAGATGCTTCATCAGCATCATC'


a10000 = "AAGTTGGTACCCTCTATTTATGCCCGGATCTTGATCTCCAGACAGGGGGTAAAGGCATGGGCCAGTTACTACCCGTATTTAGGTTGTATTCCGCATCTGAAGGCGCCGTAGTGA" \
         "TAGGCGCTGAACTGAATGCATAATGGCCAATTTGACACCTGTGGTTGTCCTCACCAATACCTGGCCCTGTCGCTCCTAATACCCCGAAGCATAGAGCAGGTCCTAACCGGATAA" \
         "CTCAGCTAACAGAAACTCCCCCAAGAACTAAGCACACCCAATGTGAACGTAGTCCGCTAGTGCTAGCGCTTCCTTACAGCCTTTCCTTATGGTATCTATGAGCTGGCCTAGTAT" \
         "ACAGGTTCTCCGACAACCAAGCCTCTCGCTGCGTTCGAGCACTGCCCGATGGCTTTGACGCGAGAGCGCTGGGTCTCATAATAAGATGGGGCGCTGTAGCGTAGTATCCCTCTC" \
         "GAGGGGACCCCGTAATGATGACATAGGTACATGCTGATAGAGGGGTCGACGGTCATTAATAACGTCCGGCTCGGCCACCCCTAGACTAGAGGGGAGAAGTTTCAGTATCTCTCG" \
         "TTTTGAATGGTACATATAAGCCTAAAGACGAGGGTAGGGTCACTAAAACTAAGTGAGCAACGTGCGGTACTGTCCTAGGCGGGCTTGACATTATACTCACTACGTTGGTTTCGC" \
         "GATGAGTCACAGGACTTTTCAGACCATGTGTCTGCCTCTAGGACCAATGGCTGGGTGTTGGTATACAACAGAGTCATTCATTTACGTCGTATATTCTAATACCACTCTTCACAC" \
         "GTCGAAATTTTCTGAGTTTCGACTACGCTTGTGAGCACTTCCTACTTGGTTAAGCAAGTGTGGGACGGCCTTCTTGGGCCAGGACGTAGGTTCCGCTGACAGTACAACGGAGAC" \
         "CAGAAAAGCTATTCAAGAGAGACATGGTACAGTTCTGTATGCATAAGCGTGCCCCTTAGCGCAACTGGCGTATACCGTCGATTCAGGG" \
         "AAGTTGGTACCCTCTATTTATGCCCGGATCTTGATCTCCAGACAGGGGGTAAAGGCATGGGCCAGTTACTACCCGTATTTAGGTTGTATTCCGCATCTGAAGGCGCCGTAGTGA" \
         "TAGGCGCTGAACTGAATGCATAATGGCCAATTTGACACCTGTGGTTGTCCTCACCAATACCTGGCCCTGTCGCTCCTAATACCCCGAAGCATAGAGCAGGTCCTAACCGGATAA" \
         "CTCAGCTAACAGAAACTCCCCCAAGAACTAAGCACACCCAATGTGAACGTAGTCCGCTAGTGCTAGCGCTTCCTTACAGCCTTTCCTTATGGTATCTATGAGCTGGCCTAGTAT" \
         "ACAGGTTCTCCGACAACCAAGCCTCTCGCTGCGTTCGAGCACTGCCCGATGGCTTTGACGCGAGAGCGCTGGGTCTCATAATAAGATGGGGCGCTGTAGCGTAGTATCCCTCTC" \
         "GAGGGGACCCCGTAATGATGACATAGGTACATGCTGATAGAGGGGTCGACGGTCATTAATAACGTCCGGCTCGGCCACCCCTAGACTAGAGGGGAGAAGTTTCAGTATCTCTCG" \
         "TTTTGAATGGTACATATAAGCCTAAAGACGAGGGTAGGGTCACTAAAACTAAGTGAGCAACGTGCGGTACTGTCCTAGGCGGGCTTGACATTATACTCACTACGTTGGTTTCGC" \
         "GATGAGTCACAGGACTTTTCAGACCATGTGTCTGCCTCTAGGACCAATGGCTGGGTGTTGGTATACAACAGAGTCATTCATTTACGTCGTATATTCTAATACCACTCTTCACAC" \
         "GTCGAAATTTTCTGAGTTTCGACTACGCTTGTGAGCACTTCCTACTTGGTTAAGCAAGTGTGGGACGGCCTTCTTGGGCCAGGACGTAGGTTCCGCTGACAGTACAACGGAGAC" \
         "CAGAAAAGCTATTCAAGAGAGACATGGTACAGTTCTGTATGCATAAGCGTGCCCCTTAGCGCAACTGGCGTATACCGTCGATTCAGGG" \
         "AAGTTGGTACCCTCTATTTATGCCCGGATCTTGATCTCCAGACAGGGGGTAAAGGCATGGGCCAGTTACTACCCGTATTTAGGTTGTATTCCGCATCTGAAGGCGCCGTAGTGA" \
         "TAGGCGCTGAACTGAATGCATAATGGCCAATTTGACACCTGTGGTTGTCCTCACCAATACCTGGCCCTGTCGCTCCTAATACCCCGAAGCATAGAGCAGGTCCTAACCGGATAA" \
         "CTCAGCTAACAGAAACTCCCCCAAGAACTAAGCACACCCAATGTGAACGTAGTCCGCTAGTGCTAGCGCTTCCTTACAGCCTTTCCTTATGGTATCTATGAGCTGGCCTAGTAT" \
         "ACAGGTTCTCCGACAACCAAGCCTCTCGCTGCGTTCGAGCACTGCCCGATGGCTTTGACGCGAGAGCGCTGGGTCTCATAATAAGATGGGGCGCTGTAGCGTAGTATCCCTCTC" \
         "GAGGGGACCCCGTAATGATGACATAGGTACATGCTGATAGAGGGGTCGACGGTCATTAATAACGTCCGGCTCGGCCACCCCTAGACTAGAGGGGAGAAGTTTCAGTATCTCTCG" \
         "TTTTGAATGGTACATATAAGCCTAAAGACGAGGGTAGGGTCACTAAAACTAAGTGAGCAACGTGCGGTACTGTCCTAGGCGGGCTTGACATTATACTCACTACGTTGGTTTCGC" \
         "GATGAGTCACAGGACTTTTCAGACCATGTGTCTGCCTCTAGGACCAATGGCTGGGTGTTGGTATACAACAGAGTCATTCATTTACGTCGTATATTCTAATACCACTCTTCACAC" \
         "GTCGAAATTTTCTGAGTTTCGACTACGCTTGTGAGCACTTCCTACTTGGTTAAGCAAGTGTGGGACGGCCTTCTTGGGCCAGGACGTAGGTTCCGCTGACAGTACAACGGAGAC" \
         "CAGAAAAGCTATTCAAGAGAGACATGGTACAGTTCTGTATGCATAAGCGTGCCCCTTAGCGCAACTGGCGTATACCGTCGATTCAGGG" \
         "AAGTTGGTACCCTCTATTTATGCCCGGATCTTGATCTCCAGACAGGGGGTAAAGGCATGGGCCAGTTACTACCCGTATTTAGGTTGTATTCCGCATCTGAAGGCGCCGTAGTGA" \
         "TAGGCGCTGAACTGAATGCATAATGGCCAATTTGACACCTGTGGTTGTCCTCACCAATACCTGGCCCTGTCGCTCCTAATACCCCGAAGCATAGAGCAGGTCCTAACCGGATAA" \
         "CTCAGCTAACAGAAACTCCCCCAAGAACTAAGCACACCCAATGTGAACGTAGTCCGCTAGTGCTAGCGCTTCCTTACAGCCTTTCCTTATGGTATCTATGAGCTGGCCTAGTAT" \
         "ACAGGTTCTCCGACAACCAAGCCTCTCGCTGCGTTCGAGCACTGCCCGATGGCTTTGACGCGAGAGCGCTGGGTCTCATAATAAGATGGGGCGCTGTAGCGTAGTATCCCTCTC" \
         "GAGGGGACCCCGTAATGATGACATAGGTACATGCTGATAGAGGGGTCGACGGTCATTAATAACGTCCGGCTCGGCCACCCCTAGACTAGAGGGGAGAAGTTTCAGTATCTCTCG" \
         "TTTTGAATGGTACATATAAGCCTAAAGACGAGGGTAGGGTCACTAAAACTAAGTGAGCAACGTGCGGTACTGTCCTAGGCGGGCTTGACATTATACTCACTACGTTGGTTTCGC" \
         "GATGAGTCACAGGACTTTTCAGACCATGTGTCTGCCTCTAGGACCAATGGCTGGGTGTTGGTATACAACAGAGTCATTCATTTACGTCGTATATTCTAATACCACTCTTCACAC" \
         "GTCGAAATTTTCTGAGTTTCGACTACGCTTGTGAGCACTTCCTACTTGGTTAAGCAAGTGTGGGACGGCCTTCTTGGGCCAGGACGTAGGTTCCGCTGACAGTACAACGGAGAC" \
         "CAGAAAAGCTATTCAAGAGAGACATGGTACAGTTCTGTATGCATAAGCGTGCCCCTTAGCGCAACTGGCGTATACCGTCGATTCAGGG" \
         "AAGTTGGTACCCTCTATTTATGCCCGGATCTTGATCTCCAGACAGGGGGTAAAGGCATGGGCCAGTTACTACCCGTATTTAGGTTGTATTCCGCATCTGAAGGCGCCGTAGTGA" \
         "TAGGCGCTGAACTGAATGCATAATGGCCAATTTGACACCTGTGGTTGTCCTCACCAATACCTGGCCCTGTCGCTCCTAATACCCCGAAGCATAGAGCAGGTCCTAACCGGATAA" \
         "CTCAGCTAACAGAAACTCCCCCAAGAACTAAGCACACCCAATGTGAACGTAGTCCGCTAGTGCTAGCGCTTCCTTACAGCCTTTCCTTATGGTATCTATGAGCTGGCCTAGTAT" \
         "ACAGGTTCTCCGACAACCAAGCCTCTCGCTGCGTTCGAGCACTGCCCGATGGCTTTGACGCGAGAGCGCTGGGTCTCATAATAAGATGGGGCGCTGTAGCGTAGTATCCCTCTC" \
         "GAGGGGACCCCGTAATGATGACATAGGTACATGCTGATAGAGGGGTCGACGGTCATTAATAACGTCCGGCTCGGCCACCCCTAGACTAGAGGGGAGAAGTTTCAGTATCTCTCG" \
         "TTTTGAATGGTACATATAAGCCTAAAGACGAGGGTAGGGTCACTAAAACTAAGTGAGCAACGTGCGGTACTGTCCTAGGCGGGCTTGACATTATACTCACTACGTTGGTTTCGC" \
         "GATGAGTCACAGGACTTTTCAGACCATGTGTCTGCCTCTAGGACCAATGGCTGGGTGTTGGTATACAACAGAGTCATTCATTTACGTCGTATATTCTAATACCACTCTTCACAC" \
         "GTCGAAATTTTCTGAGTTTCGACTACGCTTGTGAGCACTTCCTACTTGGTTAAGCAAGTGTGGGACGGCCTTCTTGGGCCAGGACGTAGGTTCCGCTGACAGTACAACGGAGAC" \
         "CAGAAAAGCTATTCAAGAGAGACATGGTACAGTTCTGTATGCATAAGCGTGCCCCTTAGCGCAACTGGCGTATACCGTCGATTCAGGG" \
         "AAGTTGGTACCCTCTATTTATGCCCGGATCTTGATCTCCAGACAGGGGGTAAAGGCATGGGCCAGTTACTACCCGTATTTAGGTTGTATTCCGCATCTGAAGGCGCCGTAGTGA" \
         "TAGGCGCTGAACTGAATGCATAATGGCCAATTTGACACCTGTGGTTGTCCTCACCAATACCTGGCCCTGTCGCTCCTAATACCCCGAAGCATAGAGCAGGTCCTAACCGGATAA" \
         "CTCAGCTAACAGAAACTCCCCCAAGAACTAAGCACACCCAATGTGAACGTAGTCCGCTAGTGCTAGCGCTTCCTTACAGCCTTTCCTTATGGTATCTATGAGCTGGCCTAGTAT" \
         "ACAGGTTCTCCGACAACCAAGCCTCTCGCTGCGTTCGAGCACTGCCCGATGGCTTTGACGCGAGAGCGCTGGGTCTCATAATAAGATGGGGCGCTGTAGCGTAGTATCCCTCTC" \
         "GAGGGGACCCCGTAATGATGACATAGGTACATGCTGATAGAGGGGTCGACGGTCATTAATAACGTCCGGCTCGGCCACCCCTAGACTAGAGGGGAGAAGTTTCAGTATCTCTCG" \
         "TTTTGAATGGTACATATAAGCCTAAAGACGAGGGTAGGGTCACTAAAACTAAGTGAGCAACGTGCGGTACTGTCCTAGGCGGGCTTGACATTATACTCACTACGTTGGTTTCGC" \
         "GATGAGTCACAGGACTTTTCAGACCATGTGTCTGCCTCTAGGACCAATGGCTGGGTGTTGGTATACAACAGAGTCATTCATTTACGTCGTATATTCTAATACCACTCTTCACAC" \
         "GTCGAAATTTTCTGAGTTTCGACTACGCTTGTGAGCACTTCCTACTTGGTTAAGCAAGTGTGGGACGGCCTTCTTGGGCCAGGACGTAGGTTCCGCTGACAGTACAACGGAGAC" \
         "CAGAAAAGCTATTCAAGAGAGACATGGTACAGTTCTGTATGCATAAGCGTGCCCCTTAGCGCAACTGGCGTATACCGTCGATTCAGGG" \
         "AAGTTGGTACCCTCTATTTATGCCCGGATCTTGATCTCCAGACAGGGGGTAAAGGCATGGGCCAGTTACTACCCGTATTTAGGTTGTATTCCGCATCTGAAGGCGCCGTAGTGA" \
         "TAGGCGCTGAACTGAATGCATAATGGCCAATTTGACACCTGTGGTTGTCCTCACCAATACCTGGCCCTGTCGCTCCTAATACCCCGAAGCATAGAGCAGGTCCTAACCGGATAA" \
         "CTCAGCTAACAGAAACTCCCCCAAGAACTAAGCACACCCAATGTGAACGTAGTCCGCTAGTGCTAGCGCTTCCTTACAGCCTTTCCTTATGGTATCTATGAGCTGGCCTAGTAT" \
         "ACAGGTTCTCCGACAACCAAGCCTCTCGCTGCGTTCGAGCACTGCCCGATGGCTTTGACGCGAGAGCGCTGGGTCTCATAATAAGATGGGGCGCTGTAGCGTAGTATCCCTCTC" \
         "GAGGGGACCCCGTAATGATGACATAGGTACATGCTGATAGAGGGGTCGACGGTCATTAATAACGTCCGGCTCGGCCACCCCTAGACTAGAGGGGAGAAGTTTCAGTATCTCTCG" \
         "TTTTGAATGGTACATATAAGCCTAAAGACGAGGGTAGGGTCACTAAAACTAAGTGAGCAACGTGCGGTACTGTCCTAGGCGGGCTTGACATTATACTCACTACGTTGGTTTCGC" \
         "GATGAGTCACAGGACTTTTCAGACCATGTGTCTGCCTCTAGGACCAATGGCTGGGTGTTGGTATACAACAGAGTCATTCATTTACGTCGTATATTCTAATACCACTCTTCACAC" \
         "GTCGAAATTTTCTGAGTTTCGACTACGCTTGTGAGCACTTCCTACTTGGTTAAGCAAGTGTGGGACGGCCTTCTTGGGCCAGGACGTAGGTTCCGCTGACAGTACAACGGAGAC" \
         "CAGAAAAGCTATTCAAGAGAGACATGGTACAGTTCTGTATGCATAAGCGTGCCCCTTAGCGCAACTGGCGTATACCGTCGATTCAGGG" \
         "AAGTTGGTACCCTCTATTTATGCCCGGATCTTGATCTCCAGACAGGGGGTAAAGGCATGGGCCAGTTACTACCCGTATTTAGGTTGTATTCCGCATCTGAAGGCGCCGTAGTGA" \
         "TAGGCGCTGAACTGAATGCATAATGGCCAATTTGACACCTGTGGTTGTCCTCACCAATACCTGGCCCTGTCGCTCCTAATACCCCGAAGCATAGAGCAGGTCCTAACCGGATAA" \
         "CTCAGCTAACAGAAACTCCCCCAAGAACTAAGCACACCCAATGTGAACGTAGTCCGCTAGTGCTAGCGCTTCCTTACAGCCTTTCCTTATGGTATCTATGAGCTGGCCTAGTAT" \
         "ACAGGTTCTCCGACAACCAAGCCTCTCGCTGCGTTCGAGCACTGCCCGATGGCTTTGACGCGAGAGCGCTGGGTCTCATAATAAGATGGGGCGCTGTAGCGTAGTATCCCTCTC" \
         "GAGGGGACCCCGTAATGATGACATAGGTACATGCTGATAGAGGGGTCGACGGTCATTAATAACGTCCGGCTCGGCCACCCCTAGACTAGAGGGGAGAAGTTTCAGTATCTCTCG" \
         "TTTTGAATGGTACATATAAGCCTAAAGACGAGGGTAGGGTCACTAAAACTAAGTGAGCAACGTGCGGTACTGTCCTAGGCGGGCTTGACATTATACTCACTACGTTGGTTTCGC" \
         "GATGAGTCACAGGACTTTTCAGACCATGTGTCTGCCTCTAGGACCAATGGCTGGGTGTTGGTATACAACAGAGTCATTCATTTACGTCGTATATTCTAATACCACTCTTCACAC" \
         "GTCGAAATTTTCTGAGTTTCGACTACGCTTGTGAGCACTTCCTACTTGGTTAAGCAAGTGTGGGACGGCCTTCTTGGGCCAGGACGTAGGTTCCGCTGACAGTACAACGGAGAC" \
         "CAGAAAAGCTATTCAAGAGAGACATGGTACAGTTCTGTATGCATAAGCGTGCCCCTTAGCGCAACTGGCGTATACCGTCGATTCAGGG" \
         "AAGTTGGTACCCTCTATTTATGCCCGGATCTTGATCTCCAGACAGGGGGTAAAGGCATGGGCCAGTTACTACCCGTATTTAGGTTGTATTCCGCATCTGAAGGCGCCGTAGTGA" \
         "TAGGCGCTGAACTGAATGCATAATGGCCAATTTGACACCTGTGGTTGTCCTCACCAATACCTGGCCCTGTCGCTCCTAATACCCCGAAGCATAGAGCAGGTCCTAACCGGATAA" \
         "CTCAGCTAACAGAAACTCCCCCAAGAACTAAGCACACCCAATGTGAACGTAGTCCGCTAGTGCTAGCGCTTCCTTACAGCCTTTCCTTATGGTATCTATGAGCTGGCCTAGTAT" \
         "ACAGGTTCTCCGACAACCAAGCCTCTCGCTGCGTTCGAGCACTGCCCGATGGCTTTGACGCGAGAGCGCTGGGTCTCATAATAAGATGGGGCGCTGTAGCGTAGTATCCCTCTC" \
         "GAGGGGACCCCGTAATGATGACATAGGTACATGCTGATAGAGGGGTCGACGGTCATTAATAACGTCCGGCTCGGCCACCCCTAGACTAGAGGGGAGAAGTTTCAGTATCTCTCG" \
         "TTTTGAATGGTACATATAAGCCTAAAGACGAGGGTAGGGTCACTAAAACTAAGTGAGCAACGTGCGGTACTGTCCTAGGCGGGCTTGACATTATACTCACTACGTTGGTTTCGC" \
         "GATGAGTCACAGGACTTTTCAGACCATGTGTCTGCCTCTAGGACCAATGGCTGGGTGTTGGTATACAACAGAGTCATTCATTTACGTCGTATATTCTAATACCACTCTTCACAC" \
         "GTCGAAATTTTCTGAGTTTCGACTACGCTTGTGAGCACTTCCTACTTGGTTAAGCAAGTGTGGGACGGCCTTCTTGGGCCAGGACGTAGGTTCCGCTGACAGTACAACGGAGAC" \
         "CAGAAAAGCTATTCAAGAGAGACATGGTACAGTTCTGTATGCATAAGCGTGCCCCTTAGCGCAACTGGCGTATACCGTCGATTCAGGG" \
         "AAGTTGGTACCCTCTATTTATGCCCGGATCTTGATCTCCAGACAGGGGGTAAAGGCATGGGCCAGTTACTACCCGTATTTAGGTTGTATTCCGCATCTGAAGGCGCCGTAGTGA" \
         "TAGGCGCTGAACTGAATGCATAATGGCCAATTTGACACCTGTGGTTGTCCTCACCAATACCTGGCCCTGTCGCTCCTAATACCCCGAAGCATAGAGCAGGTCCTAACCGGATAA" \
         "CTCAGCTAACAGAAACTCCCCCAAGAACTAAGCACACCCAATGTGAACGTAGTCCGCTAGTGCTAGCGCTTCCTTACAGCCTTTCCTTATGGTATCTATGAGCTGGCCTAGTAT" \
         "ACAGGTTCTCCGACAACCAAGCCTCTCGCTGCGTTCGAGCACTGCCCGATGGCTTTGACGCGAGAGCGCTGGGTCTCATAATAAGATGGGGCGCTGTAGCGTAGTATCCCTCTC" \
         "GAGGGGACCCCGTAATGATGACATAGGTACATGCTGATAGAGGGGTCGACGGTCATTAATAACGTCCGGCTCGGCCACCCCTAGACTAGAGGGGAGAAGTTTCAGTATCTCTCG" \
         "TTTTGAATGGTACATATAAGCCTAAAGACGAGGGTAGGGTCACTAAAACTAAGTGAGCAACGTGCGGTACTGTCCTAGGCGGGCTTGACATTATACTCACTACGTTGGTTTCGC" \
         "GATGAGTCACAGGACTTTTCAGACCATGTGTCTGCCTCTAGGACCAATGGCTGGGTGTTGGTATACAACAGAGTCATTCATTTACGTCGTATATTCTAATACCACTCTTCACAC" \
         "GTCGAAATTTTCTGAGTTTCGACTACGCTTGTGAGCACTTCCTACTTGGTTAAGCAAGTGTGGGACGGCCTTCTTGGGCCAGGACGTAGGTTCCGCTGACAGTACAACGGAGAC" \
         "CAGAAAAGCTATTCAAGAGAGACATGGTACAGTTCTGTATGCATAAGCGTGCCCCTTAGCGCAACTGGCGTATACCGTCGATTCAGGG"
b10000 = 'GTTCGTTCATGACTGTCTAAACCTATTCGACGTGCGCCCTTTAGAGGATCATTCTAGATT' \
         'GTATGAGACCGATAAGATGAACATTTTATCAATTCCGCGCGGGGCTACAATATGATCTTG' \
         'ATAATTGTGGTATAAGAGACGATAAAGGCGATTTTCTATCAATCCATCTGACAAACCGTC' \
         'TCTAGCATCAATGCAACGCGTTTGGTTGGCCTAGTGGCGTTAGTGAATGGGGACCAGTTC' \
         'AGTATCGCCCATCGGACTTGAACAATAAGCGTGAACGGACCCAAACTTTTATGCCCGGCC' \
         'GGTTTCGACCCCGTTGCGACGAGTTATCATTTCAGCACGAGGACATGGTCCCGGTTTGAG' \
         'ACTCGTAAAACCCTACCTAGCACGGTATTCCGGACACTAATATAAAATGAATACCTGCGA' \
         'TAATAGATCAAGCGCTACAGCCCGGGCCCAGCTACCCGGATATAAATCTAAATGTTGCAT' \
         'AAACCATTATTGTACCTCAACTTGAGTTCGATAGGCCGCGCACTGTGGCTTTGCCATGCC' \
         'TACGCTTCACCATAGACTACACGTGAAAATTCGCATTAGCCTACACGACACGCCCGAGTC' \
         'TAAATGTTCCTCGAAGAACAATGTTGCCAAAGTTCTATTGATTACACACAAGCGCACTAA' \
         'AAGACAAAATTTATGGCCAGGGGCGGTAGTAGAATAGCAAGGTGAGTTGTTCGCAGGCTA' \
         'CATGCGATGCGATAGTATACTCGCGACCGGAGGGGGTCCCACACCCTTATGCTGATATTG' \
         'CTTATGCATATGGCTACGATACAGCCGAAACCAAACGGCTAAATATTAGTACCTAGTTTC' \
         'GAAAACATGGCTTGCGCATCACCTTCCATAAGGACGACGTCGAGCCAAGCGCATAGAAGG' \
         'CTTTATAATTATAAGGACAATGGGGACATCTCGTCCTGGTGTATTCGTCCAAGTGCTTGG' \
         'TGAAATCATCACGACCCATAGATGCTTCATCAGCATCATC' \
         'GTTCGTTCATGACTGTCTAAACCTATTCGACGTGCGCCCTTTAGAGGATCATTCTAGATT' \
         'GTATGAGACCGATAAGATGAACATTTTATCAATTCCGCGCGGGGCTACAATATGATCTTG' \
         'ATAATTGTGGTATAAGAGACGATAAAGGCGATTTTCTATCAATCCATCTGACAAACCGTC' \
         'TCTAGCATCAATGCAACGCGTTTGGTTGGCCTAGTGGCGTTAGTGAATGGGGACCAGTTC' \
         'AGTATCGCCCATCGGACTTGAACAATAAGCGTGAACGGACCCAAACTTTTATGCCCGGCC' \
         'GGTTTCGACCCCGTTGCGACGAGTTATCATTTCAGCACGAGGACATGGTCCCGGTTTGAG' \
         'ACTCGTAAAACCCTACCTAGCACGGTATTCCGGACACTAATATAAAATGAATACCTGCGA' \
         'TAATAGATCAAGCGCTACAGCCCGGGCCCAGCTACCCGGATATAAATCTAAATGTTGCAT' \
         'AAACCATTATTGTACCTCAACTTGAGTTCGATAGGCCGCGCACTGTGGCTTTGCCATGCC' \
         'TACGCTTCACCATAGACTACACGTGAAAATTCGCATTAGCCTACACGACACGCCCGAGTC' \
         'TAAATGTTCCTCGAAGAACAATGTTGCCAAAGTTCTATTGATTACACACAAGCGCACTAA' \
         'AAGACAAAATTTATGGCCAGGGGCGGTAGTAGAATAGCAAGGTGAGTTGTTCGCAGGCTA' \
         'CATGCGATGCGATAGTATACTCGCGACCGGAGGGGGTCCCACACCCTTATGCTGATATTG' \
         'CTTATGCATATGGCTACGATACAGCCGAAACCAAACGGCTAAATATTAGTACCTAGTTTC' \
         'GAAAACATGGCTTGCGCATCACCTTCCATAAGGACGACGTCGAGCCAAGCGCATAGAAGG' \
         'CTTTATAATTATAAGGACAATGGGGACATCTCGTCCTGGTGTATTCGTCCAAGTGCTTGG' \
         'TGAAATCATCACGACCCATAGATGCTTCATCAGCATCATC' \
         'GTTCGTTCATGACTGTCTAAACCTATTCGACGTGCGCCCTTTAGAGGATCATTCTAGATT' \
         'GTATGAGACCGATAAGATGAACATTTTATCAATTCCGCGCGGGGCTACAATATGATCTTG' \
         'ATAATTGTGGTATAAGAGACGATAAAGGCGATTTTCTATCAATCCATCTGACAAACCGTC' \
         'TCTAGCATCAATGCAACGCGTTTGGTTGGCCTAGTGGCGTTAGTGAATGGGGACCAGTTC' \
         'AGTATCGCCCATCGGACTTGAACAATAAGCGTGAACGGACCCAAACTTTTATGCCCGGCC' \
         'GGTTTCGACCCCGTTGCGACGAGTTATCATTTCAGCACGAGGACATGGTCCCGGTTTGAG' \
         'ACTCGTAAAACCCTACCTAGCACGGTATTCCGGACACTAATATAAAATGAATACCTGCGA' \
         'TAATAGATCAAGCGCTACAGCCCGGGCCCAGCTACCCGGATATAAATCTAAATGTTGCAT' \
         'AAACCATTATTGTACCTCAACTTGAGTTCGATAGGCCGCGCACTGTGGCTTTGCCATGCC' \
         'TACGCTTCACCATAGACTACACGTGAAAATTCGCATTAGCCTACACGACACGCCCGAGTC' \
         'TAAATGTTCCTCGAAGAACAATGTTGCCAAAGTTCTATTGATTACACACAAGCGCACTAA' \
         'AAGACAAAATTTATGGCCAGGGGCGGTAGTAGAATAGCAAGGTGAGTTGTTCGCAGGCTA' \
         'CATGCGATGCGATAGTATACTCGCGACCGGAGGGGGTCCCACACCCTTATGCTGATATTG' \
         'CTTATGCATATGGCTACGATACAGCCGAAACCAAACGGCTAAATATTAGTACCTAGTTTC' \
         'GAAAACATGGCTTGCGCATCACCTTCCATAAGGACGACGTCGAGCCAAGCGCATAGAAGG' \
         'CTTTATAATTATAAGGACAATGGGGACATCTCGTCCTGGTGTATTCGTCCAAGTGCTTGG' \
         'TGAAATCATCACGACCCATAGATGCTTCATCAGCATCATC' \
         'GTTCGTTCATGACTGTCTAAACCTATTCGACGTGCGCCCTTTAGAGGATCATTCTAGATT' \
         'GTATGAGACCGATAAGATGAACATTTTATCAATTCCGCGCGGGGCTACAATATGATCTTG' \
         'ATAATTGTGGTATAAGAGACGATAAAGGCGATTTTCTATCAATCCATCTGACAAACCGTC' \
         'TCTAGCATCAATGCAACGCGTTTGGTTGGCCTAGTGGCGTTAGTGAATGGGGACCAGTTC' \
         'AGTATCGCCCATCGGACTTGAACAATAAGCGTGAACGGACCCAAACTTTTATGCCCGGCC' \
         'GGTTTCGACCCCGTTGCGACGAGTTATCATTTCAGCACGAGGACATGGTCCCGGTTTGAG' \
         'ACTCGTAAAACCCTACCTAGCACGGTATTCCGGACACTAATATAAAATGAATACCTGCGA' \
         'TAATAGATCAAGCGCTACAGCCCGGGCCCAGCTACCCGGATATAAATCTAAATGTTGCAT' \
         'AAACCATTATTGTACCTCAACTTGAGTTCGATAGGCCGCGCACTGTGGCTTTGCCATGCC' \
         'TACGCTTCACCATAGACTACACGTGAAAATTCGCATTAGCCTACACGACACGCCCGAGTC' \
         'TAAATGTTCCTCGAAGAACAATGTTGCCAAAGTTCTATTGATTACACACAAGCGCACTAA' \
         'AAGACAAAATTTATGGCCAGGGGCGGTAGTAGAATAGCAAGGTGAGTTGTTCGCAGGCTA' \
         'CATGCGATGCGATAGTATACTCGCGACCGGAGGGGGTCCCACACCCTTATGCTGATATTG' \
         'CTTATGCATATGGCTACGATACAGCCGAAACCAAACGGCTAAATATTAGTACCTAGTTTC' \
         'GAAAACATGGCTTGCGCATCACCTTCCATAAGGACGACGTCGAGCCAAGCGCATAGAAGG' \
         'CTTTATAATTATAAGGACAATGGGGACATCTCGTCCTGGTGTATTCGTCCAAGTGCTTGG' \
         'TGAAATCATCACGACCCATAGATGCTTCATCAGCATCATC' \
         'GTTCGTTCATGACTGTCTAAACCTATTCGACGTGCGCCCTTTAGAGGATCATTCTAGATT' \
         'GTATGAGACCGATAAGATGAACATTTTATCAATTCCGCGCGGGGCTACAATATGATCTTG' \
         'ATAATTGTGGTATAAGAGACGATAAAGGCGATTTTCTATCAATCCATCTGACAAACCGTC' \
         'TCTAGCATCAATGCAACGCGTTTGGTTGGCCTAGTGGCGTTAGTGAATGGGGACCAGTTC' \
         'AGTATCGCCCATCGGACTTGAACAATAAGCGTGAACGGACCCAAACTTTTATGCCCGGCC' \
         'GGTTTCGACCCCGTTGCGACGAGTTATCATTTCAGCACGAGGACATGGTCCCGGTTTGAG' \
         'ACTCGTAAAACCCTACCTAGCACGGTATTCCGGACACTAATATAAAATGAATACCTGCGA' \
         'TAATAGATCAAGCGCTACAGCCCGGGCCCAGCTACCCGGATATAAATCTAAATGTTGCAT' \
         'AAACCATTATTGTACCTCAACTTGAGTTCGATAGGCCGCGCACTGTGGCTTTGCCATGCC' \
         'TACGCTTCACCATAGACTACACGTGAAAATTCGCATTAGCCTACACGACACGCCCGAGTC' \
         'TAAATGTTCCTCGAAGAACAATGTTGCCAAAGTTCTATTGATTACACACAAGCGCACTAA' \
         'AAGACAAAATTTATGGCCAGGGGCGGTAGTAGAATAGCAAGGTGAGTTGTTCGCAGGCTA' \
         'CATGCGATGCGATAGTATACTCGCGACCGGAGGGGGTCCCACACCCTTATGCTGATATTG' \
         'CTTATGCATATGGCTACGATACAGCCGAAACCAAACGGCTAAATATTAGTACCTAGTTTC' \
         'GAAAACATGGCTTGCGCATCACCTTCCATAAGGACGACGTCGAGCCAAGCGCATAGAAGG' \
         'CTTTATAATTATAAGGACAATGGGGACATCTCGTCCTGGTGTATTCGTCCAAGTGCTTGG' \
         'TGAAATCATCACGACCCATAGATGCTTCATCAGCATCATC' \
         'GTTCGTTCATGACTGTCTAAACCTATTCGACGTGCGCCCTTTAGAGGATCATTCTAGATT' \
         'GTATGAGACCGATAAGATGAACATTTTATCAATTCCGCGCGGGGCTACAATATGATCTTG' \
         'ATAATTGTGGTATAAGAGACGATAAAGGCGATTTTCTATCAATCCATCTGACAAACCGTC' \
         'TCTAGCATCAATGCAACGCGTTTGGTTGGCCTAGTGGCGTTAGTGAATGGGGACCAGTTC' \
         'AGTATCGCCCATCGGACTTGAACAATAAGCGTGAACGGACCCAAACTTTTATGCCCGGCC' \
         'GGTTTCGACCCCGTTGCGACGAGTTATCATTTCAGCACGAGGACATGGTCCCGGTTTGAG' \
         'ACTCGTAAAACCCTACCTAGCACGGTATTCCGGACACTAATATAAAATGAATACCTGCGA' \
         'TAATAGATCAAGCGCTACAGCCCGGGCCCAGCTACCCGGATATAAATCTAAATGTTGCAT' \
         'AAACCATTATTGTACCTCAACTTGAGTTCGATAGGCCGCGCACTGTGGCTTTGCCATGCC' \
         'TACGCTTCACCATAGACTACACGTGAAAATTCGCATTAGCCTACACGACACGCCCGAGTC' \
         'TAAATGTTCCTCGAAGAACAATGTTGCCAAAGTTCTATTGATTACACACAAGCGCACTAA' \
         'AAGACAAAATTTATGGCCAGGGGCGGTAGTAGAATAGCAAGGTGAGTTGTTCGCAGGCTA' \
         'CATGCGATGCGATAGTATACTCGCGACCGGAGGGGGTCCCACACCCTTATGCTGATATTG' \
         'CTTATGCATATGGCTACGATACAGCCGAAACCAAACGGCTAAATATTAGTACCTAGTTTC' \
         'GAAAACATGGCTTGCGCATCACCTTCCATAAGGACGACGTCGAGCCAAGCGCATAGAAGG' \
         'CTTTATAATTATAAGGACAATGGGGACATCTCGTCCTGGTGTATTCGTCCAAGTGCTTGG' \
         'TGAAATCATCACGACCCATAGATGCTTCATCAGCATCATC' \
         'GTTCGTTCATGACTGTCTAAACCTATTCGACGTGCGCCCTTTAGAGGATCATTCTAGATT' \
         'GTATGAGACCGATAAGATGAACATTTTATCAATTCCGCGCGGGGCTACAATATGATCTTG' \
         'ATAATTGTGGTATAAGAGACGATAAAGGCGATTTTCTATCAATCCATCTGACAAACCGTC' \
         'TCTAGCATCAATGCAACGCGTTTGGTTGGCCTAGTGGCGTTAGTGAATGGGGACCAGTTC' \
         'AGTATCGCCCATCGGACTTGAACAATAAGCGTGAACGGACCCAAACTTTTATGCCCGGCC' \
         'GGTTTCGACCCCGTTGCGACGAGTTATCATTTCAGCACGAGGACATGGTCCCGGTTTGAG' \
         'ACTCGTAAAACCCTACCTAGCACGGTATTCCGGACACTAATATAAAATGAATACCTGCGA' \
         'TAATAGATCAAGCGCTACAGCCCGGGCCCAGCTACCCGGATATAAATCTAAATGTTGCAT' \
         'AAACCATTATTGTACCTCAACTTGAGTTCGATAGGCCGCGCACTGTGGCTTTGCCATGCC' \
         'TACGCTTCACCATAGACTACACGTGAAAATTCGCATTAGCCTACACGACACGCCCGAGTC' \
         'TAAATGTTCCTCGAAGAACAATGTTGCCAAAGTTCTATTGATTACACACAAGCGCACTAA' \
         'AAGACAAAATTTATGGCCAGGGGCGGTAGTAGAATAGCAAGGTGAGTTGTTCGCAGGCTA' \
         'CATGCGATGCGATAGTATACTCGCGACCGGAGGGGGTCCCACACCCTTATGCTGATATTG' \
         'CTTATGCATATGGCTACGATACAGCCGAAACCAAACGGCTAAATATTAGTACCTAGTTTC' \
         'GAAAACATGGCTTGCGCATCACCTTCCATAAGGACGACGTCGAGCCAAGCGCATAGAAGG' \
         'CTTTATAATTATAAGGACAATGGGGACATCTCGTCCTGGTGTATTCGTCCAAGTGCTTGG' \
         'TGAAATCATCACGACCCATAGATGCTTCATCAGCATCATC' \
         'GTTCGTTCATGACTGTCTAAACCTATTCGACGTGCGCCCTTTAGAGGATCATTCTAGATT' \
         'GTATGAGACCGATAAGATGAACATTTTATCAATTCCGCGCGGGGCTACAATATGATCTTG' \
         'ATAATTGTGGTATAAGAGACGATAAAGGCGATTTTCTATCAATCCATCTGACAAACCGTC' \
         'TCTAGCATCAATGCAACGCGTTTGGTTGGCCTAGTGGCGTTAGTGAATGGGGACCAGTTC' \
         'AGTATCGCCCATCGGACTTGAACAATAAGCGTGAACGGACCCAAACTTTTATGCCCGGCC' \
         'GGTTTCGACCCCGTTGCGACGAGTTATCATTTCAGCACGAGGACATGGTCCCGGTTTGAG' \
         'ACTCGTAAAACCCTACCTAGCACGGTATTCCGGACACTAATATAAAATGAATACCTGCGA' \
         'TAATAGATCAAGCGCTACAGCCCGGGCCCAGCTACCCGGATATAAATCTAAATGTTGCAT' \
         'AAACCATTATTGTACCTCAACTTGAGTTCGATAGGCCGCGCACTGTGGCTTTGCCATGCC' \
         'TACGCTTCACCATAGACTACACGTGAAAATTCGCATTAGCCTACACGACACGCCCGAGTC' \
         'TAAATGTTCCTCGAAGAACAATGTTGCCAAAGTTCTATTGATTACACACAAGCGCACTAA' \
         'AAGACAAAATTTATGGCCAGGGGCGGTAGTAGAATAGCAAGGTGAGTTGTTCGCAGGCTA' \
         'CATGCGATGCGATAGTATACTCGCGACCGGAGGGGGTCCCACACCCTTATGCTGATATTG' \
         'CTTATGCATATGGCTACGATACAGCCGAAACCAAACGGCTAAATATTAGTACCTAGTTTC' \
         'GAAAACATGGCTTGCGCATCACCTTCCATAAGGACGACGTCGAGCCAAGCGCATAGAAGG' \
         'CTTTATAATTATAAGGACAATGGGGACATCTCGTCCTGGTGTATTCGTCCAAGTGCTTGG' \
         'TGAAATCATCACGACCCATAGATGCTTCATCAGCATCATC' \
         'GTTCGTTCATGACTGTCTAAACCTATTCGACGTGCGCCCTTTAGAGGATCATTCTAGATT' \
         'GTATGAGACCGATAAGATGAACATTTTATCAATTCCGCGCGGGGCTACAATATGATCTTG' \
         'ATAATTGTGGTATAAGAGACGATAAAGGCGATTTTCTATCAATCCATCTGACAAACCGTC' \
         'TCTAGCATCAATGCAACGCGTTTGGTTGGCCTAGTGGCGTTAGTGAATGGGGACCAGTTC' \
         'AGTATCGCCCATCGGACTTGAACAATAAGCGTGAACGGACCCAAACTTTTATGCCCGGCC' \
         'GGTTTCGACCCCGTTGCGACGAGTTATCATTTCAGCACGAGGACATGGTCCCGGTTTGAG' \
         'ACTCGTAAAACCCTACCTAGCACGGTATTCCGGACACTAATATAAAATGAATACCTGCGA' \
         'TAATAGATCAAGCGCTACAGCCCGGGCCCAGCTACCCGGATATAAATCTAAATGTTGCAT' \
         'AAACCATTATTGTACCTCAACTTGAGTTCGATAGGCCGCGCACTGTGGCTTTGCCATGCC' \
         'TACGCTTCACCATAGACTACACGTGAAAATTCGCATTAGCCTACACGACACGCCCGAGTC' \
         'TAAATGTTCCTCGAAGAACAATGTTGCCAAAGTTCTATTGATTACACACAAGCGCACTAA' \
         'AAGACAAAATTTATGGCCAGGGGCGGTAGTAGAATAGCAAGGTGAGTTGTTCGCAGGCTA' \
         'CATGCGATGCGATAGTATACTCGCGACCGGAGGGGGTCCCACACCCTTATGCTGATATTG' \
         'CTTATGCATATGGCTACGATACAGCCGAAACCAAACGGCTAAATATTAGTACCTAGTTTC' \
         'GAAAACATGGCTTGCGCATCACCTTCCATAAGGACGACGTCGAGCCAAGCGCATAGAAGG' \
         'CTTTATAATTATAAGGACAATGGGGACATCTCGTCCTGGTGTATTCGTCCAAGTGCTTGG' \
         'TGAAATCATCACGACCCATAGATGCTTCATCAGCATCATC' \
         'GTTCGTTCATGACTGTCTAAACCTATTCGACGTGCGCCCTTTAGAGGATCATTCTAGATT' \
         'GTATGAGACCGATAAGATGAACATTTTATCAATTCCGCGCGGGGCTACAATATGATCTTG' \
         'ATAATTGTGGTATAAGAGACGATAAAGGCGATTTTCTATCAATCCATCTGACAAACCGTC' \
         'TCTAGCATCAATGCAACGCGTTTGGTTGGCCTAGTGGCGTTAGTGAATGGGGACCAGTTC' \
         'AGTATCGCCCATCGGACTTGAACAATAAGCGTGAACGGACCCAAACTTTTATGCCCGGCC' \
         'GGTTTCGACCCCGTTGCGACGAGTTATCATTTCAGCACGAGGACATGGTCCCGGTTTGAG' \
         'ACTCGTAAAACCCTACCTAGCACGGTATTCCGGACACTAATATAAAATGAATACCTGCGA' \
         'TAATAGATCAAGCGCTACAGCCCGGGCCCAGCTACCCGGATATAAATCTAAATGTTGCAT' \
         'AAACCATTATTGTACCTCAACTTGAGTTCGATAGGCCGCGCACTGTGGCTTTGCCATGCC' \
         'TACGCTTCACCATAGACTACACGTGAAAATTCGCATTAGCCTACACGACACGCCCGAGTC' \
         'TAAATGTTCCTCGAAGAACAATGTTGCCAAAGTTCTATTGATTACACACAAGCGCACTAA' \
         'AAGACAAAATTTATGGCCAGGGGCGGTAGTAGAATAGCAAGGTGAGTTGTTCGCAGGCTA' \
         'CATGCGATGCGATAGTATACTCGCGACCGGAGGGGGTCCCACACCCTTATGCTGATATTG' \
         'CTTATGCATATGGCTACGATACAGCCGAAACCAAACGGCTAAATATTAGTACCTAGTTTC' \
         'GAAAACATGGCTTGCGCATCACCTTCCATAAGGACGACGTCGAGCCAAGCGCATAGAAGG' \
         'CTTTATAATTATAAGGACAATGGGGACATCTCGTCCTGGTGTATTCGTCCAAGTGCTTGG' \
         'TGAAATCATCACGACCCATAGATGCTTCATCAGCATCATC'

run_test(a1000,b1000,2)

if long_run:
    run_test(a10000,b10000,2)


'''
**OUTPUT** (with long_run = True)
Running LCS Brute on size 10 by 10
The solution with a length of 5 is GCCGT
Time elapsed is 0.0005018711090087891

Running LCS Recursive on size 10 by 10
The solution with a length of 5 is GCCGT
Time elapsed is 0.007575035095214844

Running LCS Dynamic on size 10 by 10
The solution with a length of 5 is GCCGT
Time elapsed is 0.0

Running LCS Brute on size 15 by 15
The solution with a length of 11 is ATTAGATATTG
Time elapsed is 0.0030100345611572266

Running LCS Recursive on size 15 by 15
The solution with a length of 11 is ATTAGATATTG
Time elapsed is 0.17942023277282715

Running LCS Dynamic on size 15 by 15
The solution with a length of 11 is ATTAGATATTG
Time elapsed is 0.0005013942718505859

Running LCS Brute on size 20 by 20
The solution with a length of 10 is GAAGGAGTTA
Time elapsed is 1.1120269298553467

Running LCS Recursive on size 20 by 20
The solution with a length of 10 is GAAGGAGTTA
Time elapsed is 106.73156905174255

Running LCS Dynamic on size 20 by 20
The solution with a length of 10 is GAAGGAGTTA
Time elapsed is 0.0005011558532714844

Running LCS Dynamic on size 100 by 100
Hundreds of characters: . Done!
The solution with a length of 64 is GGGTTCGCCCCGGATCTGTTACAGCAAAGTCTGTAGCAGCTAATTAGGGCGTGTGTCAGGCTGA
Time elapsed is 0.007993459701538086

Running LCS Dynamic on size 1000 by 1000
Hundreds of characters: .......... Done!
The solution with a length of 639 is GTTGTTCATGACTGTCTCCAGACGGGTAAGGATCCAGTTATACCGATAGGTTTATTCCGCCGGGGCCTATGATCTGATAATGATAAGAGACATGGGTTTTCACAATCCTGCCCGTCTCTAATCAAGCAAGCGGTCCTAGGATAATCAGTCAGATCCCCAAGAACTAAGCACACCCAAACTATCCCGGCCGTTTCGCCCCGTTCGACGAGTTACATTTCGACAACAGTCCCGGTTGAGACTGCCCATGCTTTCCGGACCTTATAAAAGATCCTGCGTATATCCCTCAGGGGCCCGTAATATAAATCATGTGATAAACCATTATACTCCGGTCGACCCGACTGGGGAGAGTTCAATCTCCGTGAATTCATTAGCCTAAGACAGGGTAGTCCTAAAACAATGGCAAGTCTATGTCCACGGCTGACATTTATCCAGGGGCGTGAGTACAGGATTTTCGCAGGTCTGCTCTAGAATGGCGGGGGGTCAACAGGTATTCTTATGATATCTAATACACCACACGGAAATTTTCTAGTTTCGAACGCTTGGACACTTCCATAAGGACGCTCGGCCAACGTAGGGCTAATAAAGGACAAGCATTCGCTGGTACGTTCTGTATCATACGCCCTAGATGCTTCTCGATCA
Time elapsed is 0.8164641857147217

Running LCS Dynamic on size 10000 by 10000
Hundreds of characters: .................................................................................................... Done!
The solution with a length of 6505 is GTTGTCCTCTATTTATGCCCCTTGATCTCAGAGGGGAAAGATGCATTATACCCGGGGTATTGATCTGAAGGGTATAAGGCGTAACGATCATAATCCATTGACACCGTCTCACCAATACCTGGCCTGTGCTTATGAAGCATAGACGCCCCGGATAACTAGCTAACGACCCAAACTAGCCCCCGTGACGTTCGCAGTTACTTCCACAGCTTCCTTTGGATCTAACCCTATACAGGTTTCCGACACAATTGCTGCGTTAGATCAGGCTACGCGGGCGCTGGTATAATAAATGTTGCATACCTTAGACCTAATTGACATAGGCGCGATGGGTCGACGCTTAATAACTCCGGTCGCATAGCTAAGGGAGAAGTTTCAGACTTCGTTTTGATTACAAAAGCCTAAAGACGAGGGGGGTATAAATAGCAAGGGGTTGTTCGGGCTTGACATTATACTCCACGGGGGGGTCCAACTTAGCTGTTTGCTTAGCAATGGCTGTGGAACAAAGGCTATTTAGTCTATTTCAAAACTCTTCACACTCAAACGAGTCGACCGCGTAGACTTTATTTTAAGCAATGGGGACTCTGCCGGACGTAGGTTGTGAAACACAGACCAAAGCTTCAAGACATGTCGTTCTGATGCTAAGCGTGCCCCTTAGAGGATCTCGATTAGGGAAGTGACTTTTTATCCCGGTCTTGATCTGAAGGGTAAAGGCATGGCGTTCTACCCATTGGTTTAGCATCTGAACGCGTGTGTAGGGCGATGAATGCATAATGCCATTTGAACTGTGGGCCCAAATATGCCCGGCCTTACCCCGAAGCATAGAGCAGGTCCCGGTAACTCGTAAAACCCCCAGACTACCACCAATTAAAGTCCGCTATGTAGCGCTACAGCCCGGGAGCTCCGTATACAGTTCTAAACCAAGTCTCCTGGTTCGAGCCGCCCGTGGCTTTGCCAGACGCTTCCATAATAAGTGCGCTTAGCTAGACCCCCGAGCCCCGAAGAACAAGTCAGCTATGATCACGGCATAAAAGCGGCCGGCATAGATAGAGGGAGTTTCAGTACTCTCGTTTTGAAGGTACATTAGCTAAGCAGTAGGCTACTAAGGACAACGGCTATGTCCTAGCGGGCTTGACATTATAACACGTGGCGCGATAGAAGGCTTTTAAATGGCTGCTCTGCCTGGTGGGTGTTGGTAAAACAGACCATAGTGTTATCAATCACTCTTCAACGTCAAACTATTCGACTCGCTTTGAGACTTCTATTGTAGAAGTGTGACTTCTTGGGCCAGACGTATTGTGGTAAAGAGACGAAAAGCATTCAAACATTACAGTTCTGATCATAAGCGTGTTGGCCTGGCGTTAGTGAAGGGAAGTTGTACCCCATCGGACTTGACAAAGGGGGAAACATGGGCCGTTTACCCGTTAGGTTTATTCGCACGAGGCGCCGGTTGGCTGAACTATGCATATGGCCAATTTGAACCTGGTTGTCACCTACGCCCGGCCCATACCCGGATAAATCTAAGGATAACCATAGTCCCAACTAGCAACCCATGTGGTTGCATGCTACGCTTCCTACACCTTTCCTTAGTACAGACGCCAGTTAAGTTCCCGAAACAAGTTGCCGTTCTATTTTACCAAGCGCCTCAAAAAGAGGGGCGGTAGTAGATAGGGGAGTTGTGCAGGTACATGCGATGCGATATATACTCGCGACCGGAGGGGGAATTAGTATTTGTTTGAATGGTACATAAGCCAAACAAGGCTAAATAAGTACCTGTTTCGCGGCTTGACATTATAACACGTGGCGCGATAGAAGGCTTTTAAATGGCTGCTCTGCCTGGTGGGTGTTGGTAAAACAGACCATAGTGTTATCAATCACTCTTCAACGTCAAACTATTCGACTCGCTTTGAGACTTCTATTGTAGAAGTGTGACTTCTTGGGCCAGACGTATTGTGGTAAAGAGACGAAAAGCATTCAAACATTACAGTTCTGATCATAAGCGTGTTGGCCTGGCGTTAGTGAAGGGAAGTTGTACCCCATCGGACTTGACAAAGGGGGAAACATGGGCCGTTTACCCGTTAGGTTTATTCGCACGAGGCGCCGGTTGGCTGAACTATGCATATGGCCAATTTGAACCTGGTTGTCACCTACGCCCGGCCCATACCCGGATAAATCTAAGGATAACCATAGTCCCAACTAGCAACCCATGTGGTTGCATGCTACGCTTCCTACACCTTTCCTTAGTACAGACGCCAGTTAAGTTCCCGAAACAAGTTGCCGTTCTATTTTACCAAGCGCCTCAAAAAGAGGGGCGGTAGTAGATAGGGGAGTTGTGCAGGTACATGCGATGCGATATATACTCGCGACCGGAGGGGGAATTAGTATTTGTTTGAATGGTACATAAGCCAAACAAGGCTAAATAAGTACCTGTTTCGCGGCTTGACATTATAACACGTGGCGCGATAGAAGGCTTTTAAATGGCTGCTCTGCCTGGTGGGTGTTGGTAAAACAGACCATAGTGTTATCAATCACTCTTCAACGTCAAACTATTCGACTCGCTTTGAGACTTCTATTGTAGAAGTGTGACTTCTTGGGCCAGACGTATTGTGGTAAAGAGACGAAAAGCATTCAAACATTACAGTTCTGATCATAAGCGTGTTGGCCTGGCGTTAGTGAAGGGAAGTTGTACCCCATCGGACTTGACAAAGGGGGAAACATGGGCCGTTTACCCGTTAGGTTTATTCGCACGAGGCGCCGGTTGGCTGAACTATGCATATGGCCAATTTGAACCTGGTTGTCACCTACGCCCGGCCCATACCCGGATAAATCTAAGGATAACCATAGTCCCAACTAGCAACCCATGTGGTTGCATGCTACGCTTCCTACACCTTTCCTTAGTACAGACGCCAGTTAAGTTCCCGAAACAAGTTGCCGTTCTATTTTACCAAGCGCCTCAAAAAGAGGGGCGGTAGTAGATAGGGGAGTTGTGCAGGTACATGCGATGCGATATATACTCGCGACCGGAGGGGGAATTAGTATTTGTTTGAATGGTACATAAGCCAAACAAGGCTAAATAAGTACCTGTTTCGCGGCTTGACATTATAACACGTGGCGCGATAGAAGGCTTTTAAATGGCTGCTCTGCCTGGTGGGTGTTGGTAAAACAGACCATAGTGTTATCAATCACTCTTCAACGTCAAACTATTCGACTCGCTTTGAGACTTCTATTGTAGAAGTGTGACTTCTTGGGCCAGACGTATTGTGGTAAAGAGACGAAAAGCATTCAAACATTACAGTTCTGATCATAAGCGTGTTGGCCTGGCGTTAGTGAAGGGAAGTTGTACCCCATCGGACTTGACAAAGGGGGAAACATGGGCCGTTTACCCGTTAGGTTTATTCGCACGAGGCGCCGGTTGGCTGAACTATGCATATGGCCAATTTGAACCTGGTTGTCACCTACGCCCGGCCCATACCCGGATAAATCTAAGGATAACCATAGTCCCAACTAGCAACCCATGTGGTTGCATGCTACGCTTCCTACACCTTTCCTTAGTACAGACGCCAGTTAAGTTCCCGAAACAAGTTGCCGTTCTATTTTACCAAGCGCCTCAAAAAGAGGGGCGGTAGTAGATAGGGGAGTTGTGCAGGTACATGCGATGCGATATATACTCGCGACCGGAGGGGGAATTAGTATTTGTTTGAATGGTACATAAGCCAAACAAGGCTAAATAAGTACCTGTTTCGCGGCTTGACATTATAACACGTGGCGCGATAGAAGGCTTTTAAATGGCTGCTCTGCCTGGTGGGTGTTGGTAAAACAGACCATAGTGTTATCAATCACTCTTCAACGTCAAACTATTCGACTCGCTTTGAGACTTCTATTGTAGAAGTGTGACTTCTTGGGCCAGACGTATTGTGGTAAAGAGACGAAAAGCATTCAAACATTACAGTTCTGATCATAAGCGTGTTGGCCTGGCGTTAGTGAAGGGAAGTTGTACCCCATCGGACTTGACAAAGGGGGAAACATGGGCCGTTTACCCGTTAGGTTTATTCGCACGAGGCGCCGGTTGGCTGAACTATGCATATGGCCAATTTGAACCTGGTTGTCACCTACGCCCGGCCCATACCCGGATAAATCTAAGGATAACCATAGTCCCAACTAGCAACCCATGTGGTTGCATGCTACGCTTCCTACACCTTTCCTTAGTACAGACGCCAGTTAAGTTCCCGAAACAAGTTGCCGTTCTATTTTACCAAGCGCCTCAAAAAGAGGGGCGGTAGTAGATAGGGGAGTTGTGCAGGTACATGCGATGCGATATATACTCGCGACCGGAGGGGGAATTAGTATTTGTTTGAATGGTACATAAGCCAAACAAGGCTAAATAAGTACCTGTTTCGCGGCTTGACATTATAACACGTGGCGCGATAGAAGGCTTTTAAATGGCTGCTCTGCCTGGTGGGTGTTGGTAAAACAGACCATAGTGTTATCAATCACTCTTCAACGTCAAACTATTCGACTCGCTTTGAGACTTCTATTGTAGAAGTGTGACTTCTTGGGCCAGACGTATTGTGGTAAAGAGACGAAAAGCATTCAAACATTACAGTTCTGATCATAAGCGTGTTGGCCTGGCGTTAGTGAAGGGAAGTTGTACCCCATCGGACTTGACAAAGGGGGAAACATGGGCCGTTTACCCGTTAGGTTTATTCGCACGAGGCGCCGGTTGGCTGAACTATGCATATGGCCAATTTGAACCTGGTTGTCACCTACGCCCGGCCCATACCCGGATAAATCTAAGGATAACCATAGTCCCAACTAGCAACCCATGTGGTTGCATGCTACGCTTCCTACACCTTTCCTTAGTACAGACGCCAGTTAAGTTCCCGAAACAAGTTGCCGTTCTATTTTACCAAGCGCCTCAAAAAGAGGGGCGGTAGTAGATAGGGGAGTTGTGCAGGTACATGCGATGCGATATATACTCGCGACCGGAGGGGGAATTAGTATTTGTTTGAATGGTACATAAGCCAAACAAGGCTAAATAAGTACCTGTTTCGCGGCTTGACATTATAACACGTGGCGCGATAGAAGGCTTTTAAATGGCTGCTCTGCCTGGTGGGTGTTGGTAAAACAGACCATAGTGTTATCAATCACTCTTCAACGTCAAACTATTCGACTCGCTTTGAGACTTCTATTGTAGAAGTGTGACTTCTTGGGCCAGACGTATTGTGGTAAAGAGACGAAAAGCATTCAAACATTACAGTTCTGATCATAAGCGTGTTGGCCTGGCGTTAGTGAAGGGAAGTTGTACCCCATCGGACTTGACAAAGGGGGAAACATGGGCCGTTTACCCGTTAGGTTTATTCGCACGAGGCGCCGGTTGGCTGAACTATGCATATGGCCAATTTGAACCTGGTTGTCACCTACGCCCGGCCCATACCCGGATAAATCTAAGGATAACCATAGTCCCAACTAGCAACCCATGTGGTTGCATGCTACGCTTCCTACACCTTTCCTTAGTACAGACGCCAGTTAAGTTCCCGAAACAAGTTGCCGTTCTATTTTACCAAGCGCCTCAAAAAGAGGGGCGGTAGTAGATAGGGGAGTTGTGCAGGTACATGCGATGCGATATATACTCGCGACCGGAGGGGGAATTAGTATTTGTTTGAATGGTACATAAGCCAAACAAGGCTAAATAAGTACCTGTTTCGCGGCTTGACATTATAACACGTGGCGCGATAGAAGGCTTTTAAATGGCTGCTCTGCCTGGTGGGTGTTGGTAAAACAGACCATAGTGTTATCAATCACTCTTCAACGTCAAACTATTCGACTCGCTTTGAGACTTCTATTGTAGAAGTGTGACTTCTTGGGCCAGACGTATTGTGGTAAAGAGACGAAAAGCATTCAAACATTACAGTTCTGATCATAAGCGTGTTGGCCTGGCGTTAGTGAAGGGAAGTTGTACCCCATCGGACTTGAACAAAAGCTGGGCCAAACTTTTATGCCGCCGGCGCCGTTGCGACGAGTATCATTTCACCGGGACATGGCCCGTGCTCTAAACCCACTAGCAGGTACCGGACACTAAATAAAATGAACCTGGAATAGTCCGCTACAGCCCCCAGCTCCGGATATATCTAAAGTTCTAAACCAATTGTCTCAACTGCGATGGCCGCGCCTGGGCTTTGATGCCTACGTTCCCTAGACCCGTAAATGCATAGTACACGAACGCGGTCTAAAGTCCTCGAAGACAAGGAAAGTTCTATTGATTACAAAAGCCTAAAGACGAGGGGGGTATAAATAGCAAGGGGTTGTTCGGGCTTGACATTATACTCCACGGGGGGGTCCAACTTAGCTGTTTGCTTAGCAATGGCTGTGGAACAAAGGCTATTTAGTCTATTTCAAAACTCTTCACACTCAAACGAGTCGACCGCGTAGACTTTATTTTAAGCAATGGGGACTCTCGCTGGTGTACGTCCAAGGCTTGGTGAAATCATACGCCCTAGATGCTTCTCGATCA
Time elapsed is 74.54926919937134


Process finished with exit code 0

'''
